frontend/src/components/common/Text/Text.stories.ts
frontend/src/components/common/Text/Text.styled.ts
frontend/src/components/common/Text/Text.tsx
frontend/src/types/size.ts

> #9 
size는 xxs, xs, md, lg, xl, xxl 6개 대응가능
weight는 normal, bold, extraBold 3개 대응 가능
지금 size에 font-size만 있는데 line-height도 필요할까? 필요하다면 font-size에 비해 얼마 크게 잡아야할까?

[FE] 공통 Text 컴포넌트 생성

---

frontend/src/components/common/Button/Button.stories.tsx
frontend/src/components/common/Button/Button.styled.ts
frontend/src/components/common/Button/Button.tsx
frontend/src/components/common/Text/Text.styled.ts
frontend/src/components/common/Text/Text.tsx
frontend/src/styles/theme.ts
frontend/src/types/size.ts

#[FE]공통으로 사용되는 사이즈 타입 통일
> #20 
공통으로 사용되는 사이즈 타입 통일

[FE]공통으로 사용되는 사이즈 타입 통일

---

backend/src/main/java/team/teamby/teambyteam/schedule/domain/Name.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Span.java

[BE] 일정 도메인 작성

---

backend/src/main/java/team/teamby/teambyteam/teamplace/domain/Name.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepository.java
backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceException.java
backend/src/test/java/team/teamby/teambyteam/teamplace/domain/NameTest.java

> #27 
- 팀 플레이스 도메인 구현
- 팀 플레이스 이름 VO 구현
- 팀 플레이스 이름 VO 검증 테스트 
- 팀 플레이스 Exception 구현

[BE] 팀 플레이스 도메인 작성

---

backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Email.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/ProfileImageUrl.java
backend/src/main/java/team/teamby/teambyteam/member/exception/MemberException.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
backend/src/test/java/team/teamby/teambyteam/member/domain/vo/EmailTest.java
backend/src/test/java/team/teamby/teambyteam/member/domain/vo/NameTest.java

> #25 
-Member 도메인 작성
- MemberTeamPlace 도메인 작성
- MemberRepository, MemberTeamPlaceRepository 구현
- Member <-> MemberTeamPlace <-> TeamPlace 연관관계 생각해보기

[BE] 멤버 도메인 작성

---

backend/src/main/java/team/teamby/teambyteam/schedule/domain/Name.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/Name.java
backend/src/test/java/team/teamby/teambyteam/schedule/domain/NameTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/domain/NameTest.java

> #39 
- VO에 null입력시 NPE가 발생하도록 수정

[BE] NULL 입력에 대한 예외 클래스 변경

---

backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Title.java
backend/src/test/java/team/teamby/teambyteam/schedule/domain/TitleTest.java
backend/src/test/resources/h2-data.sql

> #40 
- Schedule domain의 Name vo -> Title vo로 변경

[BE] 일정명 필드 vo 네이밍 변경

---

backend/src/test/resources/h2-data.sql

#28 
팀플레이스 더미 데이터를 추가하고 스케쥴 더미데이터를 추가(초를 00초로 변경)

[BE] 팀플레이스 테스트용 더미데이터 추가

---

backend/src/test/resources/h2-data.sql

[BE] member & member_team_pace 더미 데이터 추가

---

frontend/src/components/Calendar/Calendar.stories.tsx
frontend/src/components/Calendar/Calendar.styled.ts
frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/Calendar/DateCell/DateCell.stories.tsx
frontend/src/components/Calendar/DateCell/DateCell.styled.ts
frontend/src/components/Calendar/DateCell/DateCell.tsx
frontend/src/styles/theme.ts
frontend/src/utils/parseDate.test.ts
frontend/src/utils/parseDate.ts

> close #36 
Calendar 컴포넌트 UI 구현

[FE] Calendar 컴포넌트 UI 구현

---

backend/build.gradle
backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
backend/src/main/java/team/teamby/teambyteam/member/configuration/AuthPrincipal.java
backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberArgumentResolver.java
backend/src/main/java/team/teamby/teambyteam/member/configuration/dto/MemberEmailDto.java

#49 
Bearer token에서 email을 추출하는 Argument Resolver 구현

[BE] Bearer token에서 email을 추출하는 Argument Resolver 구현

---

frontend/src/apis/fetch.ts
frontend/src/mocks/handlers/calendar.ts
frontend/src/mocks/handlers/index.ts
frontend/src/types/schedule.ts

> close #52 
캘린더 일정 등록 및 조회 모킹 구현

[FE] 캘린더 일정 등록 및 조회 모킹 구현

---

backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java

> #55
- entity도메인에 id를 제외한 파라미터를 받는 생성자 추가

[BE] entity에 id를 제외한 나머지를 파라미터로 받는 생성자 작성

---

backend/src/test/resources/h2-data.sql

[BE] data.fix/be/data.sql 버그 fix

---

backend/src/test/resources/h2-data.sql
backend/src/test/resources/h2-reset-pk.sql

[BE] fix: 2개 이상의 테스트 실행시 h2-data.sql 오류 수정

---

backend/build.gradle

[BE] RestAssured 의존성 추가

---

backend/src/test/java/team/teamby/teambyteam/common/AcceptanceTest.java

> #68 
- AcceptanceTest 슈퍼 클래스 구현

[BE] AcceptanceTest 슈퍼 클래스 구현

---

frontend/src/mocks/handlers/calendar.ts
frontend/src/types/schedule.ts

[FE] 캘린더 일정 제목 필드 변경 반영

---

backend/src/test/java/team/teamby/teambyteam/fixtures/ScheduleFixtures.java
backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/docs/ScheduleApiDocsTest.java

> #84 
Fixture, Test 한글 -> 영어로 리팩토링

[BE] Fixture, Test 한글 -> 영어로 리팩토링

---

.github/workflows/frontend-ci.yml

> close #99 
github actions ci 스크립트 node cache 수정

[FE] github actions ci 스크립트 node cache 수정

---

.github/workflows/backend-ci.yml

[BE] 백엔드 CI 워크플로우 생성

---

.github/workflows/backend-dev-branch-build-and-upload.yml

[BE] dev브랜치 머지시 빌드 & artifact 업로드 깃헙플로우 추가

---

frontend/src/App.tsx
frontend/src/components/Calendar/Calendar.stories.tsx
frontend/src/components/Calendar/Calendar.styled.ts
frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
frontend/src/components/ScheduleBar/ScheduleBar.tsx
frontend/src/constants/calendar.ts
frontend/src/mocks/fixtures/schedules.ts
frontend/src/utils/generateScheduleBars.ts

[FE] schedule bar 렌더링 구현

---

frontend/.husky/pre-commit
frontend/package-lock.json
frontend/package.json
frontend/webpack.config.js

[FE] webpack 환경변수관련 설정

---

.github/workflows/backend-dev-branch-build-and-upload.yml

[BE] cd 워크플로우 작성

---

backend/.gitignore
backend/build.gradle

[BE] dev DB 관련 설정

---

frontend/src/apis/http.ts

> close #127 
http 추상화 로직 수정 및 에러 throw 로직 추가

[FE] http 추상화 로직 수정 및 에러 throw 로직 추가

---

frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
frontend/src/components/ScheduleBar/ScheduleBar.tsx
frontend/src/utils/generateScheduleBars.ts

> close #122 
ScheduleBar 스타일 수정

[FE] ScheduleBar 스타일 수정

---

.github/workflows/backend-dev-branch-build-and-upload.yml

[BE] CD yml Syntax Error 수정

---

.github/workflows/backend-ci.yml
.github/workflows/backend-dev-branch-build-and-upload.yml

- 테스트 자동화시 ubuntu 22.04에서 실행
- 배포 자동화

[BE] ci cd workflow 수정

---

frontend/src/apis/http.ts
frontend/src/apis/schedule.ts
frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/ScheduleEditModal/ScheduleEditModal.stories.tsx
frontend/src/components/ScheduleEditModal/ScheduleEditModal.styled.ts
frontend/src/components/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/ScheduleModal/ScheduleModal.stories.tsx
frontend/src/components/ScheduleModal/ScheduleModal.tsx
frontend/src/constants/calendar.ts
frontend/src/hooks/queries/useDeleteSchedule.ts
frontend/src/hooks/queries/useFetchSchedules.ts
frontend/src/hooks/queries/useModifySchedule.ts
frontend/src/hooks/queries/useSendSchedule.ts
frontend/src/hooks/schedule/useScheduleAddModal.ts
frontend/src/hooks/schedule/useScheduleEditModal.ts
frontend/src/mocks/handlers/calendar.ts
frontend/src/types/schedule.ts

> close #111
일정 수정 api 연결 및 배포된 서버와 연동 테스트

[FE] 일정 수정 api 연결

---

frontend/src/utils/generateScheduleBars.ts
frontend/src/utils/generateUuid.ts

> close #140 
crypto.randomUUID를 대체하는 유틸함수 작성

[FE] crypto.randomUUID를 대체하는 유틸함수 작성

---

backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Email.java
backend/src/main/java/team/teamby/teambyteam/teamplace/configuration/TeamPlaceInterceptor.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceException.java
backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/docs/ScheduleApiDocsTest.java

#30
Teamplace 참가 여부를 확인하는 TeamPlaceInterceptor 구현

[BE] Teamplace 참가 여부를 확인하는 TeamPlaceInterceptor 구현

---

.github/workflows/backend-dev-branch-build-and-upload.yml

>
- 배포시 설정파일 artifact 노출 문제 해결
- 설정파일을 셀프호스티드 러너로 이동
- deploy.sh 파일 secret 수정
- 지금 이전 자료들은 수동으로 지워둠

[BE] 배포시 배포용 application.yml 파일 artifact 노출 문제 해결

---

.github/workflows/backend-dev-branch-build-and-upload.yml

[BE] 개발 서버 배포 자동화 버튼 제거

---

frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
frontend/src/components/ScheduleBar/ScheduleBar.tsx
frontend/src/components/ScheduleModal/ScheduleModal.tsx
frontend/src/hooks/queries/useDeleteSchedule.ts
frontend/src/hooks/schedule/useScheduleAddModal.ts
frontend/src/hooks/schedule/useScheduleEditModal.ts
frontend/src/hooks/useCalendar.ts
frontend/src/types/typeGuard.ts
frontend/src/utils/formatISOString.test.ts
frontend/src/utils/formatISOString.ts

> 
- 캘린더 관련 코드 일부 리팩토링
- 타입 가드 적용
- 매직 넘버 제거
- 일관성에 맞게 메서드, props 등의 네이밍 수정

[FE] 캘린더 관련 코드 일부 리팩토링

---

frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/IntegratedCalendar/IntegratedCalendar.stories.tsx
frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
frontend/src/components/ScheduleEditModal/ScheduleEditModal.stories.tsx
frontend/src/components/ScheduleModal/ScheduleModal.stories.tsx
frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.stories.ts
frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.styled.ts
frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.tsx
frontend/src/components/common/Header/Header.stories.tsx

[FE] 하루 스케줄이 3개 초과일 때 보여줄 더보기 컴포넌트 구현

---

backend/src/main/java/team/teamby/teambyteam/TeamByTeamApplication.java
backend/src/main/java/team/teamby/teambyteam/global/domain/BaseEntity.java
backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
backend/src/test/resources/h2-data.sql

> #194 
- 구성 사항
- createdAt, updatedAt
- 기존 엔티티에 상속 추가
- 테스트 db에 업데이트, 생성 시간 추가

[BE] BaseEntity 작성

---

frontend/.eslintrc.json
frontend/package-lock.json
frontend/package.json
frontend/src/components/common/Menu/Menu.stories.tsx
frontend/src/components/common/Menu/Menu.styled.ts
frontend/src/components/common/Menu/Menu.tsx
frontend/src/hooks/useClickOutside.ts
frontend/src/hooks/useKeydownEffect.ts

> close #191 
- 공통 menu 컴포넌트 구현
- useEffect dependencies rule 체크를 위한 eslint-plugin-react-hooks 설치
추후 스타일링 및 props 확장 고려하기

[FE] 공통 menu 컴포넌트 구현

---

backend/src/main/java/team/teamby/teambyteam/feed/domain/Feed.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedRepository.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedThread.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedType.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/Notification.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/ScheduleNotification.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/vo/Content.java
backend/src/main/java/team/teamby/teambyteam/feed/exception/FeedException.java
backend/src/test/java/team/teamby/teambyteam/feed/domain/FeedRepositoryTest.java

[BE] 팀 피드 엔티티 구현

---

.github/workflows/frontend-cd.yml
frontend/package-lock.json
frontend/package.json
frontend/src/apis/http.ts
frontend/webpack.config.js

> close #93 #190 
- 프론트엔드 CD workflow 작성
- develop 브랜치에 merge 되는 경우 실행
- dotenv-webpack 패키지를 [dotenv](https://www.npmjs.com/package/dotenv)로 교체
- 다운로드 수, 최근 유지보수가 되었는지 등을 고려하여 dotenv가 좀 더 안정적이라고 판단
- [workflow에서 .env 파일 생성](https://ji5485.github.io/post/2021-06-26/create-env-with-github-actions-secrets/)
- [DefinePlugin - webpack](https://webpack.kr/plugins/define-plugin)

[FE] 프론트엔드 CD workflow 작성

---

backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamCalendarScheduleController.java
backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java

[BE] 단일 일정 api url 변경

---

backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java

> 단순 리팩터링 이슈 생성 x
- 팀플레이스 서비스에서 사용하지 않는 memberRepository 제거
- 해당 repository는 MyCalenderService분리시 제거되었어야하지만 놓침

[BE] 팀플레이스 일정 서비스에서 사용하지 않는 필드 제거

---

backend/src/main/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleService.java
backend/src/main/java/team/teamby/teambyteam/schedule/presentation/MyCalendarScheduleController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/ScheduleFixtures.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MyCalendarScheduleAcceptanceFixtures.java
backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/MyCalendarScheduleAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleServiceTest.java

> #155 
- 통합 캘린더 하루 일정 조회 기능 구현

[BE] 통합 캘린더 하루 일정 조회 기능 구현

---

frontend/src/styles/theme.ts

[FE] teamColor 충돌 해결

---

frontend/src/hooks/schedule/useScheduleAddModal.ts

[FE] 제거된 함수 import 문 제거

---

frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/ScheduleModal/ScheduleModal.tsx

[FE] 디자인 깨지는 현상 수정

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/dto/GoogleTokenResponse.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/dto/OAuthMember.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/dto/TokenResponse.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/client/GoogleOAuthClient.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/client/OAuthClient.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/config/GoogleOAuthProperties.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/util/GoogleOAuthUriGenerator.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/util/OAuthUriGenerator.java
backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/resources/application.yml
backend/src/test/resources/application.yml

#259 
구글 계정을 이용한 로그인/회원가입 기능 구현
Google OAuth 2.0 공식문서
https://developers.google.com/identity/protocols/oauth2/web-server?hl=ko#handlingresponse
Google OpenID Connect 공식문서
https://developers.google.com/identity/openid-connect/openid-connect?hl=ko#getcredentials

[BE] 구글 OAuth 로그인 기능 추가

---

frontend/.storybook/preview.tsx
frontend/src/apis/feed.ts
frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.stories.tsx
frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
frontend/src/hooks/queries/useSendNoticeThread.ts
frontend/src/hooks/queries/useSendThread.ts
frontend/src/hooks/thread/useThreadAddBottomSheet.ts
frontend/src/mocks/handlers/feed.ts
frontend/src/types/feed.ts

> close #183 #184 
- 팀 피드, 공지 작성 api 연결

[FE] 팀 피드, 공지 작성 api 연결

---

frontend/src/components/MyCalendar/MyCalendar.styled.ts
frontend/src/components/MyCalendar/MyCalendar.tsx
frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.styled.ts
frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.tsx
frontend/src/components/common/SideBar/SideBar.stories.ts
frontend/src/components/common/SideBar/SideBar.styled.ts
frontend/src/components/common/SideBar/SideBar.tsx
frontend/src/mocks/fixtures/schedules.ts
frontend/src/styles/theme.ts

[FE]통합 일정 사이드바 구현

---

frontend/package-lock.json
frontend/package.json
frontend/public/mockServiceWorker.js
frontend/src/App.tsx
frontend/src/components/Calendar/Calendar.styled.ts
frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/MyCalendar/MyCalendar.styled.ts
frontend/src/components/MyCalendar/MyCalendar.tsx
frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.styled.ts
frontend/src/components/common/SideBar/SideBar.styled.ts
frontend/src/components/common/SideBar/SideBar.tsx
frontend/src/components/pages/PageTemplate/PageTemplate.styled.ts
frontend/src/components/pages/PageTemplate/PageTemplate.tsx
frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.styled.ts
frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.tsx

> close #293 
임시로 캘린더 페이지 디자인도 고쳤습니다.

[FE]페이지 템플릿 구현

---

backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleWithTeamPlaceIdResponse.java

[BE] fix: response 오타 수정

---

frontend/src/components/MyCalendar/MyCalendar.stories.tsx
frontend/src/components/MyCalendar/MyCalendar.tsx
frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.stories.ts
frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.tsx
frontend/src/components/common/SideBar/SideBar.tsx
frontend/src/hooks/queries/useFetchTeamPlaces.ts
frontend/src/utils/getInfoByTeamPlaceId.ts

>  #114 
현재는 사이드바에만 적용해놔서 이슈 close 안합니다. 
요토꺼 머지되면 지금 냅다 박아둔 색상 관련해서 다 조회로직 연결해둘예정이에요

[FE]사이드 바 팀플레이스 조회 로직 연결

---

backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java

[BE] 소속 팀플레이스인지 확인할 수 없는 버그 fix

---

frontend/src/components/Notification/Notification.stories.ts
frontend/src/components/Notification/Notification.styled.ts
frontend/src/components/Notification/Notification.tsx

> close #311
- Notification 디자인 수정

[FE] Notification 디자인 수정

---

frontend/src/components/Notification/Notification.styled.ts
frontend/src/components/Notification/Notification.tsx

> close #316 
- Notification이 보이지 않는 현상 수정

[FE] Notification이 보이지 않는 현상 수정

---

frontend/src/components/pages/PageTemplate/PageTemplate.styled.ts

간단해서 이슈없음
참고로 제 컴퓨터 ㄱ기준으로 작업했어요

[FE] pageTemplate width 줄이기

---

frontend/.storybook/preview.tsx
frontend/src/components/Calendar/Calendar.stories.tsx
frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/DailyScheduleModal/DailyScheduleModal.styled.ts
frontend/src/components/DailyScheduleModal/DailyScheduleModal.tsx
frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
frontend/src/components/ScheduleBar/ScheduleBar.tsx
frontend/src/components/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/ScheduleModal/ScheduleModal.tsx
frontend/src/components/ThreadList/ThreadList.tsx
frontend/src/components/common/Header/Header.styled.ts
frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/NavigationBar/NavigationBar.tsx
frontend/src/components/common/TeamPlaceMenu/TeamPlaceMenu.stories.tsx
frontend/src/components/common/TeamPlaceMenu/TeamPlaceMenu.styled.ts
frontend/src/components/common/TeamPlaceMenu/TeamPlaceMenu.tsx
frontend/src/components/pages/TempLandingPage/TempLandingPage.styled.ts
frontend/src/components/pages/TempLandingPage/TempLandingPage.tsx
frontend/src/contexts/TeamPlaceContext.tsx
frontend/src/hooks/schedule/useScheduleAddModal.ts
frontend/src/hooks/schedule/useScheduleEditModal.ts
frontend/src/hooks/thread/useThreadAddBottomSheet.ts
frontend/src/index.tsx
frontend/src/styles/theme.ts
frontend/src/types/team.ts
frontend/src/utils/getInfoByTeamPlaceId.ts

> close #326 
헤더 팀 선택 메뉴구현
기존 만들어둔 TeamPlaceContext에 선택된 팀의 정보 추가
기존 매직넘버로 넣었던 teamPlaceId들 다 변경

[FE]팀 전환 기능 구현

---

frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/common/Header/Header.tsx
frontend/src/contexts/TeamPlaceContext.tsx
frontend/src/hooks/schedule/useScheduleAddModal.ts

[FE] 새로고침 팀 초기화 버그 수정

---

frontend/src/components/Thread/Thread.stories.ts

[FE] Thread 스토리북 테스트 수정

---

frontend/src/hooks/schedule/useScheduleAddModal.ts

> 핫픽스라 이슈 제외
- 시간 설정하지 않고 종일 일정 등록 실패 현상 수정

[FE] 시간 설정하지 않고 종일 일정 등록 실패 현상 수정

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java

#366 
/login에 redirect하면서 url에 param으로 토큰을 주도록 변경

[BE] 최종 redirect url의 param에 토큰을 포함하도록 구현

---

frontend/src/apis/auth.ts
frontend/src/pages/LandingPage/LandingPage.styled.ts
frontend/src/pages/LandingPage/LandingPage.tsx

[FE] 구글 로그인 테스트 버튼 구현

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/dto/GoogleLoginUrlResponse.java

> 
- get method. body로 담아주도록 변경

[BE] 구글 oauth시 로그인 url을 redirect가 아닌 body로 담아주도록 변경

---

frontend/src/apis/auth.ts
frontend/src/pages/LandingPage/LandingPage.tsx

- 로그인 버튼 클릭시 구글 로그인 redirect 구현

[FE] 로그인 버튼 클릭시 구글 로그인 redirect 구현

---

frontend/src/App.tsx
frontend/src/constants/routes.tsx
frontend/src/pages/LoginPage/LoginPage.tsx

[FE]소셜 로그인 accesstToken 로컬에 저장하는 기능

---

frontend/src/pages/LoginPage/LoginPage.tsx

[FE] 로그인 성공시 페이지 이동

---

frontend/src/apis/http.ts

[FE] 로그인한 유저 정보로 API 요청 보내기

---

frontend/src/components/common/SideBar/SideBar.styled.ts
frontend/src/components/feed/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
frontend/src/hooks/schedule/useScheduleAddModal.ts
frontend/src/pages/TeamCalendarPage/TeamCalendarPage.styled.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts

> close #402 
- 종일 일정이 등록되지 않는 현상 수정
- 불필요한 스크롤바가 생기는 현상 수정
- 바텀시트에 Escape 키 입력 시 닫는 기능 추가

[FE] 종일 일정 등록 버그 수정

---

.github/workflows/backend-dev-branch-build-and-upload.yml
.github/workflows/frontend-cd.yml

[ALL] dev서버 배포 워크플로우 수정

---

.github/workflows/backend-dev-branch-build-and-upload.yml
.github/workflows/frontend-cd.yml

[ALL] 배포 워크플로우 오류 수정

---

.github/workflows/backend-dev-branch-build-and-upload.yml

[BE] 누락된 백엔드 배포 플로우 추가

---

.github/workflows/frontend-cd.yml

[FE] 프런트 배포 워크플로우 수정

---

.github/workflows/backend-ci.yml
.github/workflows/backend-deploy-dev.yml
.github/workflows/frontend-cd.yml
.github/workflows/frontend-ci.yml
.github/workflows/frontend-deploy-dev.yml

[ALL] 깃헙 워크플로우 네임 변경, 개발서버 배포 버튼 제거

---

.github/workflows/backend-deploy-dev.yml

[BE] deploy chore: add permission

---

.github/workflows/backend-deploy-dev.yml

chore: 배포 워크플로우 오류 수정

---

.github/workflows/backend-deploy-dev.yml

[BE] 배포 권한 설정 변경

---

frontend/src/assets/svg/index.ts
frontend/src/assets/svg/logout.svg
frontend/src/components/common/Header/Header.styled.ts
frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/NavigationBar/NavigationBar.tsx

> close #394 
로그아웃 기능 구현
슬랙 영상 참고 부탁
confirm 다음에 alert 띄운 이유는 없이 하니까 너무 휙 움직이는 느낌이라 추가함

[FE] 로그아웃 기능 구현

---

frontend/src/pages/LoginPage/LoginPage.tsx

> clsoe #420 
local에 저장 하자마자 밑에 useFetch에서 사용해야하기때문에 다시 useEffect 밖으로 뺌

[FE] 서버에서 로그인이 안되는 현상

---

.github/workflows/backend-deploy-dev.yml

[BE] 배포 테스트용 PR

---

frontend/src/hooks/team/useTeamJoin.ts
frontend/src/pages/JoinPage/JoinPage.tsx

[FE] 참여코드를 초대코드로 바꾸기

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java

> close #451 
멤버 이름 최대 길이 넘으면 잘라서 저장하도록 버그 수정

[BE] 멤버 이름 최대 길이 넘으면 잘라서 저장하도록 버그 수정

---

backend/.gitignore
backend/build.gradle
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/resources/application.yml
backend/src/main/resources/logback-spring.xml
backend/src/test/resources/application.yml

> #380
- Logback 적용
- test, local, dev환경 파일 추가
- stacktrace제거
- 예외상황 로깅 적용

[BE] 예외상황 로깅 구현

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java

[BE] 구글 OAuth 요청 2회 나가는 오류 수정

---

frontend/src/apis/auth.ts
frontend/src/apis/http.ts
frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
frontend/src/constants/localStorage.ts
frontend/src/hooks/queries/useSendTokenReissue.ts
frontend/src/pages/LoginPage/LoginPage.tsx

> close #463 
msw는 감이 안잡혀서 구현 못했습니다.
401일 시 제대로 로직 작동하는건 확인했습니다. (msw 중에 아무거나 상태코드 401에 error 메시지 넣으면 돼요)
onError에 토스트 넣은건 사용자가 요청을 보냈는데 토큰 때문에 씹힌거니까 그전 요청을 다시 어떻게 보내지 하는 의문에서 그냥 네트워크 에러인것처럼 눈속임 해야겠다! 라는 발상에서 나왔습니다. 거슬리면 지우거나 다른 로직 알려주시면 반영할게요

[FE] 토큰 만료시 refershToken으로 재발급 요청

---

backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
backend/src/main/java/team/teamby/teambyteam/member/application/dto/TeamPlaceResponse.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeResponse.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMemberResponse.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMembersResponse.java
backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamPlaceAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepositoryTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java

> closed #446 
- 팀 플레이스 참여 멤버 조회 기능

[BE] 팀 플레이스 참여 멤버 조회

---

frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
frontend/src/hooks/queries/useSendTokenReissue.ts

[FE] 토크 재발급 에러 발생시 렌딩으로 이동

---

frontend/src/apis/auth.ts
frontend/src/apis/feed.ts
frontend/src/apis/http.ts
frontend/src/apis/link.ts
frontend/src/apis/schedule.ts
frontend/src/apis/team.ts
frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
frontend/src/types/team.ts

> close #385
- API 응답 타입을 별도의 타입으로 관리하도록 리팩토링

[FE] API 응답 타입 리팩터링

---

.github/workflows/deploy-prod.yml

[BE] 운영서버 배포 워크플로우 추가

---

backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
backend/src/main/java/team/teamby/teambyteam/sharedlink/exception/SharedLinkException.java
backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/sharedlink/application/SharedLinkServiceTest.java

#485
1. create, delete 시 info 로깅 추가
2. 예외 로깅시 요청 정보 추가

[BE] create, delete 시 info 로깅 추가, 예외 메시지 변경, 예외 로깅시 요청 정보 추가

---

backend/src/docs/asciidoc/member.adoc
backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/member/docs/MemberApiDocsTest.java

#362
#373 
#377
#458 
member 도메인 api에 포함된 나의 정보 조회, 나의 참여한 팀플에이스 조회, 팀플레이스 탈퇴, 팀플레이스 참여 api 문서화

[BE] member 도메인 api 문서화

---

.github/workflows/deploy-prod.yml

운엉서버 배포 작성
- main branch의 tag를 기반으로 배포 진행
- 버튼 클릭시 배포 진행 (태그 선택)
- 추후 가능하다면 최신 태그(릴리즈)생성시 배포 진행 워크플로우 추가
- 백엔드와 프런트엔드 동시 배포 (하나의 워크플로우에서 배포 진행)

[ALL] 운영서버 배포 워크플로우

---

backend/src/docs/asciidoc/sharedlink.adoc
backend/src/test/java/team/teamby/teambyteam/sharedlink/docs/SharedLinkApiDocsTest.java

#487 
#488 
#489 
공유링크 추가, 조회, 삭제 api 문서화

[BE] 공유 링크 api 문서화

---

frontend/src/components/common/Header/Header.styled.ts
frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
frontend/src/components/common/NavigationBar/NavigationBar.tsx
frontend/src/components/common/SideBar/SideBar.styled.ts
frontend/src/components/common/SideBar/SideBar.tsx
frontend/src/components/feed/NoticeThread/NoticeThread.tsx
frontend/src/components/feed/Thread/Thread.tsx
frontend/src/components/link/EmptyLinkPlaceholder/EmptyLinkPlaceholder.tsx
frontend/src/components/link/LinkTable/LinkTable.tsx
frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.tsx
frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx

> close #510 
- 시맨틱 태그 적용 
- 접근성 개선
- 이미지 alt 속성 추가
- 버튼 aria-lable 추가

[FE] 시맨틱 태그 적용 및 접근성 개선

---

backend/src/main/resources/logback-spring.xml

> #380
운영서버 로깅 설정 작성
-  WARN level ( warn + error logging)
- FILE 로깅만 적용
- console 로깅 제외
- 운영서버에서 콘솔로 확인할 일 없음

[BE] 운영서버 로깅 설정 작성

---

.github/workflows/backend-deploy-dev-docs.yml
.github/workflows/deploy-prod-by-realease-tag.yml
.github/workflows/deploy-prod-latest.yml
.github/workflows/frontend-deploy-dev.yml

- 태그 기반 운영서버 배포 (롤백용)
- 최신 릴리즈 publish시 운영서버 자동 배포 (최신버젼 자동  배포)
- 개발서버 api 문서 자동 배포
- 더이상 사용 안하는 테스트용 프런트 환경변수 제거

[ALL] 배포 관련 워크플로우 추가 변경

---

backend/src/docs/asciidoc/index.adoc

- index.adoc에 도메인 adoc Include

[BE] index.adoc에 도메인 adoc Include 리팩토링

---

.github/workflows/backend-deploy-dev-docs.yml

[BE] 문서 배포 workflow 수정

---

frontend/src/components/feed/NotificationListModal/NotificationListModal.tsx
frontend/src/components/feed/ThreadList/ThreadList.tsx
frontend/src/hooks/useIntersectionObserver.ts

[FE] 피드의 마지막에서 스레드가 등록되지 않는 현상

---

frontend/webpack.config.js

> close #535 
- favicon 적용되도록 HtmlWebpackPlugin 옵션 수정
- 배포해서 테스트 필요

[FE] favicon 적용되도록 HtmlWebpackPlugin 옵션 수정

---

frontend/src/components/landing/IntroCardPile/IntroCardPile.styled.ts
frontend/src/components/landing/TeamCalendarDecoration/TeamCalendarDecoration.styled.ts

> close #537 
- 애니메이션 등장 타이밍 단축
- 캘린더의 연도-월을 표시하는 텍스트 색상 수정

[FE] 랜딩 페이지 애니메이션 등장 타이밍 수정

---

backend/src/docs/asciidoc/notice.adoc
backend/src/test/java/team/teamby/teambyteam/notice/docs/NoticeApiDocsTest.java

> #217 #219 
- 공지 등록 문서화
- 공지 조회 문서화

[BE] 공지 등록 및 조회 기능 문서화 

---

frontend/src/components/feed/NotificationListModal/NotificationListModal.styled.ts
frontend/src/hooks/team/useTeamCreate.ts
frontend/src/mocks/fixtures/threads.ts

> close #545 
- 알림 목록 컨텐츠가 줄바꿈 되도록 수정

[FE] 알림 목록 줄바꿈 수정

---

frontend/src/components/common/Header/Header.styled.ts
frontend/src/components/common/LandingHeader/LandingHeader.styled.ts

[FE] 헤더 로고 위치 고정

---

frontend/src/App.tsx
frontend/src/components/common/LandingHeader/LandingHeader.styled.ts
frontend/src/components/common/LandingHeader/LandingHeader.tsx

> close #550 
- 가입된 팀이 없는 경우 로고 클릭 시 메인 페이지 이동 방지

[FE] 가입된 팀이 없는 경우 로고 클릭 시 메인 페이지 이동 방지

---

frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
frontend/src/components/common/NavigationBar/NavigationBar.tsx
frontend/src/pages/StartPage/StartPage.tsx

> close #557 
- 시작 페이지에 뒤로가기 버튼 추가

[FE] 시작 페이지에 뒤로가기 버튼 추가

---

frontend/src/pages/JoinPage/JoinPage.tsx

[FE] 팀 참가에서 엔터누를 시 생성 페이지로 이동하는 버그

---

backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java

[BE] final 추가

---

.github/workflows/backend-deploy-dev.yml

[BE] 디렉토리 삭제 안되는 문제 해결

---

backend/src/main/java/team/teamby/teambyteam/feed/exception/FeedException.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java

[BE] 빈줄 제거

---

.github/workflows/backend-deploy-dev.yml
backend/src/main/java/team/teamby/teambyteam/auth/exception/AuthenticationException.java
backend/src/main/java/team/teamby/teambyteam/feed/exception/FeedException.java
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java

Release v1.0.2

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java

없음
url base64 디코딩 시 발생하는 문제 해결
주의: 안되면 다시해야됨

[BE] url base64 디코딩 문제 해결

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java

- idToken 캐스팅시 다른 타입에 대한 문제 해결

[BE] 캐스팅시 문제 해결

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java

Release v1.0.3

---

frontend/src/apis/auth.ts

[FE] 토큰 재발급시 중복 요청 보내는 트러블 슈팅

---

frontend/src/components/common/ProtectRoute/ProtectRoute.tsx

[FE] 토큰 재발급 동안 중복 요청 보내는 버그

---

frontend/src/apis/auth.ts
frontend/src/hooks/queries/useSendTokenReissue.ts

[토큰 재발급이 한번만 실행되는 현상

---

frontend/src/hooks/schedule/useScheduleAddModal.ts

> close #587 
- 일정 등록 시간 기본값을 09:00 ~ 10:00으로 수정

[FE] 일정 등록 시간 기본값을 09:00 ~ 10:00으로 수정

---

.gitmodules

[BE] 서브모듈 추가

---

backend/src/main/java/team/teamby/teambyteam/token/domain/Token.java

> close #472 
- 토큰 DDL 수정
-  Member에 nullable = false 추가
- refreshToken에 nullable = false, unique = true

[BE] 토큰 DDL NOT NULL, UNIQUE 설정 추가

---

frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/Menu/Menu.stories.tsx
frontend/src/components/common/Menu/Menu.tsx
frontend/src/components/common/Menu/MenuButton/MenuButton.tsx
frontend/src/components/common/Menu/MenuItem/MenuItem.styled.ts
frontend/src/components/common/Menu/MenuItem/MenuItem.tsx
frontend/src/components/common/Menu/MenuList/MenuList.tsx
frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.stories.tsx
frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.tsx
frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.stories.tsx
frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.tsx
frontend/src/constants/menu.ts
frontend/src/hooks/useListKeyboardNavigation.ts

> close #608 
- Menu 컴포넌트 키보드 탐색 기능 구현
- 위/아래 방향키, Enter, Escape 키 입력 감지
- 방향키에 따라 포커스 이동
- Enter 키 입력 시 포커스된 항목 선택
- Escape 키 입력 시 메뉴 닫기
https://so-so.dev/react/make-select/

[FE] Menu 컴포넌트 키보드 탐색 기능 구현

---

backend/src/main/java/team/teamby/teambyteam/feed/domain/Feed.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/vo/Content.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Email.java
backend/src/main/java/team/teamby/teambyteam/notice/domain/Notice.java
backend/src/main/java/team/teamby/teambyteam/notice/domain/vo/Content.java
backend/src/main/resources/application.yml
backend/src/main/resources/logback-spring.xml
backend/src/test/resources/application.yml

- jpa에서 기본 생성ddl에 Lob가 tinytext로 생성에서 text로 생성으로 변경
- logback설정파일에서 jdbc 패키지 오류 수정
- jpa dialect설정시 mysql 8버젼으로 변경
- submodule 내부 설정파일들도 변경완료
- 개발서버 db는 alter를 이용해서 tinytext -> text 변경 완료
- notice table, feed table 적용 완료

[BE] jpa설정 변경

---

frontend/src/mocks/fixtures/threads.ts
frontend/src/mocks/handlers/feed.ts
frontend/src/types/feed.ts

[FE] 팀 피드 API 수정

---

frontend/src/mocks/fixtures/threads.ts
frontend/src/mocks/handlers/feed.ts
frontend/src/types/feed.ts

woowacourse-teams/2023-team-by-team#652 머지를 취소

[FE] "팀 피드 API 수정" merge를 되돌리기

---

frontend/src/apis/team.ts
frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.tsx
frontend/src/hooks/queries/useModifyMyTeamPlaceUserInfo.ts
frontend/src/hooks/team/useTeamPlaceInfoModal.ts
frontend/src/hooks/user/useUserInfoModal.ts
frontend/src/mocks/fixtures/team.ts
frontend/src/mocks/handlers/team.ts
frontend/src/types/team.ts

> close #644 
- 팀플레이스 내 정보 수정 기능 구현

[FE] 팀플레이스 내 정보 수정 기능 구현

---

frontend/src/hooks/queries/usePrefetchSchedules.ts

> close #656 
- Prefetch를 조건부로 호출하도록 로직 수정

[FE] Prefetch를 조건부로 호출하도록 로직 수정

---

frontend/src/components/common/DateCell/DateCell.styled.ts
frontend/src/components/common/ExpandButton/ExpandButton.styled.ts
frontend/src/components/common/ExpandButton/ExpandButton.tsx
frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
frontend/src/components/feed/Thread/Thread.stories.ts
frontend/src/components/feed/Thread/Thread.styled.ts
frontend/src/components/feed/Thread/Thread.tsx
frontend/src/components/feed/ThreadList/ThreadList.tsx
frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.stories.tsx
frontend/src/constants/feed.ts
frontend/src/mocks/fixtures/threads.ts
frontend/src/styles/theme.ts

> close #627 close #628 close #629 
isMe에 따라 바뀌는 UI
작성자가 같은 스레드가 연속될 때 작성자 Info 가림
height가 500px 넘을경우 전체보기 추가
전체보기와 접기를 할 경우 어쩔 수 없이  layoutShift가 생기는데 어떻게 줄일 수 있을까
일단 놔두고 나중에 해결?

[FE] 변경된 스레드 컴포넌트 UI 구현

---

.github/workflows/deploy-prod-latest.yml
.github/workflows/frontend-deploy-dev.yml
frontend/src/apis/http.ts

[FE] 배포 스크립트 환경변수 이름 수정

---

.github/workflows/deploy-prod-latest.yml
.github/workflows/frontend-deploy-dev.yml

[FE]배포 스크립트 환경변수 파일 수정

---

frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/HeaderFallback/HeaderFallback.stories.tsx
frontend/src/components/common/HeaderFallback/HeaderFallback.styled.ts
frontend/src/components/common/HeaderFallback/HeaderFallback.tsx
frontend/src/components/common/Skeleton/Skeleton.stories.tsx
frontend/src/components/common/Skeleton/Skeleton.styled.ts
frontend/src/components/common/Skeleton/Skeleton.tsx
frontend/src/hooks/queries/useFetchUserInfo.ts
frontend/src/pages/PageTemplate/PageTemplate.tsx
frontend/src/styles/theme.ts

> close #674 
- Header 컴포넌트에 suspense 적용
- Skeleton 컴포넌트 추가
- 스토리북에서 확인 가능합니다

[FE] Header 컴포넌트에 Suspense 적용

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java
backend/src/main/resources/application.yml
backend/src/test/resources/application.yml

로그인 성공시 리다이렉트위치를 front-domain으로 고정

[BE] 로그인 성공시 리다이렉트위치를 front-domain으로 고정

---

.github/workflows/frontend-ci.yml

> close #680 
- CI 스크립트 빌드 명령어 수정

[FE] CI 스크립트 빌드 명령어 수정

---

frontend/src/hooks/team/useTeamFeedPage.ts

> close #683 
- 한글 입력 시 이벤트가 두 번 발생하는 현상 수정

[FE] 한글 입력 시 이벤트가 두 번 발생하는 현상 수정

---

frontend/src/components/common/Header/Header.tsx
frontend/src/components/feed/EmptyFeedPlaceholder/EmptyFeedPlaceholder.styled.ts
frontend/src/components/feed/EmptyFeedPlaceholder/EmptyFeedPlaceholder.tsx
frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
frontend/src/components/feed/NoticeThread/NoticeThread.tsx
frontend/src/components/feed/NotificationListModal/NotificationListModal.styled.ts
frontend/src/components/feed/Thread/Thread.styled.ts
frontend/src/components/feed/ThreadList/ThreadList.tsx
frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
frontend/src/components/user/UserInfoModal/UserInfoModal.styled.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
frontend/src/styles/theme.ts

> close #676
- 스레드 없을 시 디자인 수정
- 공지 스레드, 모달 z-index 수정
- 불필요하고 스크롤 버그를 발생시키는 알림 목록 모달 및 트리거 숨김

[FE] 스레드 없을 시 디자인 수정

---

.github/workflows/frontend-deploy-dev.yml

[All] S3에 dist 배포

---

.github/workflows/deploy-prod-by-realease-tag.yml
.github/workflows/deploy-prod-latest.yml
.github/workflows/frontend-deploy-dev.yml

s3로 배포할 수 있도록 수정
- 개발서버 배포시 최신데이터 배포하도록 변경
- 운영서버 s3배포로 전환

chore: 프런트 s3로 배포하도록 수정

---

.github/workflows/deploy-prod-by-realease-tag.yml

chore: 태그기반 프런트 배포 워크플로우 오류 수정

---

frontend/src/apis/auth.ts
frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
frontend/src/hooks/queries/useSendTokenReissue.ts

[FE]리프레쉬 토큰 헤더 저장못하는 문제 확인 작업

---

frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
frontend/src/hooks/queries/useSendTokenReissue.ts

[FE] 토큰 코드 원래대로 되돌리기

---

frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx

[FE] prefetch 주석처리

---

frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx

[FE] prefetch 주석 해제

---

frontend/src/pages/PageTemplate/PageTemplate.tsx

[FE] HeaderSuspense 삭제

---

frontend/src/hooks/queries/useFetchUserInfo.ts

- useFetchUserInfo suspense 옵션 제거
- 401 에러 해결

[FE] useFetchUserInfo suspense 옵션 제거

---

.github/workflows/deploy-prod-by-realease-tag.yml
.github/workflows/deploy-prod-latest.yml
.github/workflows/frontend-deploy-dev.yml

- s3 프런트 배포 후, 클라우드프런트 create-invalidation 요청 추가

[FE] 프런트 배포 후 클라우드프런트 캐시 삭제요청 추가

---

frontend/src/components/common/DateCell/DateCell.styled.ts
frontend/src/components/common/DateCell/DateCell.tsx

[FE] DateCell 토/일요일 색상 수정

---

.github/workflows/backend-ci.yml

**build 시 timezone setting 추가**

[BE] build 시 timezone setting 추가

---

frontend/src/apis/http.ts

[FE] 스레드 등록이 안되는 버그

---

backend/src/main/java/team/teamby/teambyteam/notice/domain/image/NoticeImage.java

> 긴급이라 X
- NoticeImage BaseEntity 상속받도록 추가

[BE] NoticeImage BaseEntity 상속받도록 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/hooks/queries/useSSE.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
frontend/src/types/polyfill.ts

> close #759 
- SSE 연결 코드 작성
- 개발 서버 배포 후 테스트 필요

[FE] sse 연결 코드 작성

---

frontend/src/hooks/queries/useSSE.ts

[FE] SSE 연결 해제 코드 작성

---

backend/src/main/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisher.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java

[BE] 설정 오류 수정

---

backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterId.java

[BE] SSE 이벤트 발행시 팀플레이스로 검사 오류 수정

---

frontend/src/hooks/queries/useSSE.ts
frontend/src/types/polyfill.d.ts
frontend/src/types/polyfill.ts

[FE] SSE 연결 확인 코드 작성

---

frontend/src/hooks/queries/useSSE.ts
frontend/src/hooks/thread/useTeamFeedPage.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

[FE] 새로운 스레드 등록 시 스크롤 하단으로 이동 구현

---

frontend/src/hooks/queries/useSSE.ts

- SSE 이벤트 수신 시 스크롤 로직 제거
- 스크롤 로직으로 인해 이벤트를 제대로 받지 못해서 임시로 로직 제거

[FE] SSE 이벤트 수신 시 스크롤 로직 제거

---

frontend/src/hooks/queries/useSSE.ts
frontend/src/hooks/thread/useTeamFeedPage.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

- 채팅 입력 시 스크롤 로직을 ResizeObserver로 리팩터링
- https://web.dev/articles/resize-observer?hl=ko
- 요토가 던져준 키워드 덕분에 간단하게 구현함

[FE] 채팅 입력 시 스크롤 로직을 ResizeObserver로 리팩터링

---

frontend/src/components/feed/ThreadList/ThreadList.tsx
frontend/src/hooks/thread/useTeamFeedPage.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

[FE] 스크롤 로직을 useEffect를 사용하도록 수정

---

frontend/src/components/feed/ThreadList/ThreadList.tsx
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

- 스크롤 버튼이 보이는 경우 새로운 채팅이 등록되어도 스크롤이 내려가지 않도록 수정

[FE] 스크롤 버튼이 보이는 경우 새로운 채팅이 등록되어도 스크롤이 내려가지 않도록 수정

---

frontend/src/components/common/Accordion/Accordion.stories.tsx
frontend/src/components/common/Accordion/Accordion.styled.tsx
frontend/src/components/common/Accordion/Accordion.tsx
frontend/src/components/common/Accordion/AccordionBody/AccordionBody.styled.ts
frontend/src/components/common/Accordion/AccordionBody/AccordionBody.tsx
frontend/src/components/common/Accordion/AccordionContext.tsx
frontend/src/components/common/Accordion/AccordionHeader/AccordionHeader.styled.tsx
frontend/src/components/common/Accordion/AccordionHeader/AccordionHeader.tsx
frontend/src/components/common/Accordion/AccordionItem/AccordionItem.styled.tsx
frontend/src/components/common/Accordion/AccordionItem/AccordionItem.tsx
frontend/src/components/common/Header/Header.tsx
frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.stories.tsx
frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.styled.ts
frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.tsx
frontend/src/components/user/UserInfoModal/UserInfoModal.stories.tsx
frontend/src/components/user/UserInfoModal/UserInfoModal.styled.ts
frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
frontend/src/constants/calendar.ts
frontend/src/constants/url.ts
frontend/src/hooks/useAccordion.ts

> clsoe #748 
언젠가 쓰일 것을 기대하며 공용 Accordion 컴포넌트 구현
자주하는 질문쪽에 회원탈퇴 숨겨둠

[FE] 고객 문의 모달 구현

---

frontend/src/index.tsx

> close #778 
- queryClient가 계속 새로 생성되는 로직 수정

[FE] queryClient가 계속 새로 생성되는 로직 수정

---

frontend/src/hooks/queries/useSSE.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

> close #782 
토큰 만료로 재발급을 하더라도 SSE에는 반영이 되지않아 연결이 끊기는 현상을 수정했습니다.

[FE] 재발급된 토큰으로 sse연결 요청하기

---

backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java

- Emitter로 이벤트 발행시 예외 발생상황 로직 변경
- 기존 : RuntimeException throw
- 변경 : emitter.completeWithError로 종료 수행

[BE] SSE emitter 예외시 행위 수정

---

frontend/src/hooks/queries/useSSE.ts

> close #782 
새로운 헤더로 요청하는게 안되서 찾아봤는데 라이브러리 제작자가 말한거 토대로 바꿔봄. 될지 안될지 모르겠음
https://github.com/Yaffle/EventSource/issues/137

[FE] SSE 재연결하는 로직 수정

---

frontend/src/hooks/queries/useSSE.ts

[FE] error event 콘솔

---

frontend/src/hooks/queries/useSSE.ts

[FE] 에러 발생시 sse 연결닫기

---

frontend/src/hooks/queries/useSSE.ts

[FE] useState 제거

---

.github/workflows/frontend-deploy-storybook.yml

[FE] 스토리북 배포 후 404 뜨는 문제 해결

---

frontend/src/hooks/queries/useSSE.ts

[FE] SSE 연결 로직 useCallback으로 감싸기

---

frontend/src/hooks/queries/useSSE.ts

[FE] sse 문제 해결

---

frontend/src/hooks/queries/useSSE.ts

[FE] console.log 확인

---

backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java

- IO예외시 emitter 종료 제거
- 레포지토리에서 completeWithError제거

[BE] SSE 이미터 설정 초기로 변경

---

frontend/src/hooks/queries/useSSE.ts

[FE] SSE 재연결 시도 로직 작성

---

frontend/src/hooks/queries/useSSE.ts

[FE] useSSE onerror 제거

---

.github/workflows/frontend-deploy-storybook.yml

[destination_dir: storybook](https://github.com/woowacourse-teams/2023-yozm-cafe/blob/main/.github/workflows/client-deploy-storybook.yml)

[FE] storybook workflow publish_dir 경로 변경

---

frontend/src/hooks/queries/useSSE.ts

[FE] SSE 토큰 갱신 로직 수정

---

backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java

- SseEmitters에서 이벤트 발행시 오류생기면 종료시키도록 추가

[BE] io예외시에 커넥션 종료시키는 기능 추가

---

backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java

- SSE runtimeException 핸들링 추가
- 로깅 한글화

[BE] SSE 예외처리 추가

---

frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
frontend/src/contexts/TokenContext.tsx
frontend/src/hooks/queries/useSSE.ts
frontend/src/hooks/queries/useSendTokenReissue.ts
frontend/src/hooks/user/useAccountDeleteModal.ts
frontend/src/hooks/user/useUserInfoModal.ts
frontend/src/pages/Error404Page/Error404Page.tsx
frontend/src/pages/LandingPage/LandingPage.tsx
frontend/src/pages/LoginPage/LoginPage.tsx

> close #806 
잘 작동하는지 함께 꼼꼼하게 확인해주세요! 
수고했어요 다들

[FE] accessToken 설정, 삭제하는 로직 tokenContext로 대체

---

frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx

- 살짝 부담스러웠던 모달 디자인 수정
AS-IS
TO-BE

[FE] Schedule 관련 모달 디자인 수정

---

frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
frontend/src/components/link/LinkTable/LinkTable.styled.ts
frontend/src/components/link/LinkTable/LinkTable.tsx

[FE] 링크 관련 디자인 수정

---

frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts

- 모아보기 페이지에서 링크 등록 모달 잘리는 현상 수정

[FE] 모아보기 페이지에서 링크 등록 모달 잘리는 현상 수정

---

frontend/src/hooks/queries/useSendNoticeThread.ts
frontend/src/hooks/queries/useSendThread.ts

[FE] 등록 성공 시 조회 쿼리 무효화 구문 삭제

---

backend/src/main/resources/application.yml
backend/src/test/resources/application.yml

- 설정파일 최신화
- SSE 연결 시간 변경 : 1분 -> 5분
- hikari cp 설정 : 5

[BE] 설정파일 업데이트

---

README.md

[ALL] README 업데이트

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadWithCacheServiceTest.java

- 오류 내용 : 최신 21개째부터가 최신값으로 캐싱이 되어있음!!!

[BE] 캐싱 비활성화

---

frontend/src/hooks/queries/useSendNoticeThread.ts

> #822 
제가 실수로 삭제해버린.. 공지입니다ㅠㅠ

[FE] 공지 등록 후 공지 쿼리 무효화 추가

---

frontend/src/components/common/Menu/MenuButton/MenuButton.tsx

> close #824 
- Menu가 focus 된 경우 위/아래 방향키 입력 시 열리도록 구현

[FE] Menu가 focus 된 경우 위/아래 방향키 입력 시 열리도록 구현

---

frontend/public/index.html

> close #827 
- 검색 결과에 대한 정보 제공을 위한 meta tag 추가

[FE] 검색 결과에 대한 정보 제공을 위한 meta tag 추가

---

frontend/package-lock.json
frontend/src/apis/feed.ts
frontend/src/components/common/Menu/MenuList/MenuList.tsx
frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
frontend/src/components/team/TeamExitModal/TeamExitModal.tsx
frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
frontend/src/hooks/schedule/useScheduleAddModal.ts
frontend/src/hooks/schedule/useScheduleEditModal.ts
frontend/src/hooks/team/useTeamExitModal.ts
frontend/src/hooks/team/useTeamPlaceInfoModal.ts
frontend/src/hooks/thread/useImageUpload.tsx
frontend/src/hooks/thread/useTeamFeedPage.ts
frontend/src/hooks/useBottomSheet.ts
frontend/src/hooks/useCalendar.ts
frontend/src/hooks/useClickOutside.ts
frontend/src/hooks/user/useUserInfoModal.ts

기본 내보내기로 되어있던 훅들 다 고쳤습니다
사용안한ㄴ import 삭제했습니다
npm i 하니까 package-lock이 변경되네요? 왜지

[FE] 컨벤션에 맞게 리팩터링

---

frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
frontend/src/hooks/queries/useSSE.ts
frontend/src/index.tsx
frontend/src/pages/PageTemplate/PageTemplate.tsx
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

> close #852 
- useSSE를 ProtectRoute에서 호출하도록 수정
- 개발 서버 배포 후 확인 필요

[FE] useSSE를 ProtectRoute에서 호출하도록 수정

---

.github/workflows/deploy-prod-by-realease-tag.yml
.github/workflows/deploy-prod-latest.yml
.github/workflows/frontend-deploy-dev.yml
backend/src/main/resources/logback-spring.xml

- 서버이전에 맞춰 배포 워크플로우 변경
- 서버 application.yml변경
- 개발서버에서 콘솔, 파일 중복 로깅 -> 파일 단일로깅으로 변경

[ALL] 서버이전 관련 설정, 배포 워크플로우등 변경

---

frontend/src/hooks/queries/useSSE.ts

[FE] console.log 추가

---

frontend/src/hooks/queries/useSSE.ts

[FE] 콘솔 출력 데이터 형태 변경

---

frontend/src/hooks/queries/useSSE.ts

[FE] 데이터 타입 확인

---

frontend/src/hooks/queries/useSSE.ts

[FE] sse data 콘솔 수정

---

frontend/src/hooks/queries/useSSE.ts
frontend/src/pages/PageTemplate/PageTemplate.tsx

[FE] teamPlace 전환시 SSE 끊고 다시 연결하기

---

frontend/src/hooks/queries/useSSE.ts
frontend/src/mobilePages/M_PageTemplate/M_PageTemplate.tsx

[FE]팀플레이스 전환시 sse 에서 teamPlaceId console

---

frontend/src/hooks/queries/useSSE.ts

[FE]아이디 비교 로직 추가

---

frontend/src/hooks/queries/useSSE.ts

[FE] SSE 연결을 useCallback로 감싸 한번만 작동하도록 변경

---

frontend/src/hooks/queries/useSSE.ts

[FE] SSE 중복 연결 버그 픽스

---

frontend/src/components/feed/NoticeThread/NoticeThread.stories.tsx
frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
frontend/src/components/feed/NoticeThread/NoticeThread.tsx
frontend/src/components/feed/ThumbnailList/ThumbnailList.styled.ts
frontend/src/components/feed/ThumbnailList/ThumbnailList.tsx
frontend/src/components/feed/ViewableThumbnail/ViewableThumbnail.styled.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

[FE] 공지에 사진 올라갔을 경우 UI 수정

---

frontend/src/constants/query.ts
frontend/src/hooks/queries/useSSE.ts

[FE] 채팅 setQueryData 후 콘솔 추가
> #883 
채팅 query에 대한 콘솔 추가

[FE] 채팅 setQueryData 후 콘솔 추가

---

frontend/src/hooks/queries/useSSE.ts

[FE] 채팅 SSE의 setQuery의 데이터 타입 변경

---

frontend/src/hooks/queries/useSSE.ts

[FE] sse로 받은 event data를 객체로 parse

---

frontend/src/components/feed/ThreadList/ThreadList.tsx

[FE] threadPages 변경시 콘솔 추가

---

README.md

- 채팅 성능 개선
- 일부 캘린더 일정이 안보이던 버그 수정
- 보고있는 달 전, 후 달에만 포함되지만 캘린더 끝부분에 있는 일정 안보임 수정
- 일정 등록, 수정시 사용자 편의성 향상
- 모바일 브라우저 화면 짤림 버그 수정

[ALL] Release 1.6.0

---

frontend/src/components/feed/ThreadList/ThreadList.tsx

[FE] ThreadList에 존재하는 console.log 제거

---

README.md

gif을 위로 올리고 멤버를 내림,
gif 화질 몇개 수정함

[ALL] README gif수정 및 내용 순서 변경

---

backend/src/main/java/team/teamby/teambyteam/sse/domain/emitter/SseEmitters.java

SseEmitters objectMapper에 JavaTimeModule추가

[BE] SSE이벤트 발행시 Json Parsing 에러 해결

---

.github/workflows/backend-ci.yml
.github/workflows/backend-deploy-dev-docs.yml
.github/workflows/backend-deploy-dev.yml
.github/workflows/deploy-prod-by-realease-tag.yml
.github/workflows/deploy-prod-latest.yml
.github/workflows/frontend-ci.yml
.github/workflows/frontend-deploy-dev.yml
.github/workflows/frontend-deploy-storybook.yml

- deprecate된 node버젼 사용 github action들 버젼 업그래이드
- 백엔드 config를 서브모듈에서 가져오도록 변경

[ALL] 배포 워크플로우 수정

---

README.md

[ALL] docs: reesase 1.6.1

---

backend/src/main/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisher.java

- 누락된 SSE 발행 이벤트 리스닝 추가
- 기존 도메인에서 구현 -> SSE 도메인에서 구현으로 바뀐 후 실수로 적응을 못해 누락된 부분 추가

[BE] 누락된 SSE 이벤트 발행 추가

---

frontend/src/hooks/queries/useFetchDailySchedules.ts

[FE] 하루 전체 일정에서 쿼리 매개변수 형식 변경

---

backend/src/main/java/team/teamby/teambyteam/icalendar/application/PeriodicIcalendarPublishService.java

> #945 
- ics 배포과정 디버깅을 위한 로깅 추가

[BE] ics 배포과정 로깅 추가

---

README.md
backend/src/main/java/team/teamby/teambyteam/icalendar/application/PeriodicIcalendarPublishService.java
backend/src/main/java/team/teamby/teambyteam/icalendar/domain/ical4j/ICal4jParser.java
backend/src/main/java/team/teamby/teambyteam/icalendar/domain/ical4j/VEventParser.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java

Release 1.6.5

---

backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleResponse.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java

> close #944 
- Schedule 응답 response 바디에 description 필드 추가
- 해당 필드는 optional
- 자세한 내용은 api문서 확인

[BE] schedule response에 description 추가

---

.github/workflows/backend-deploy-dev-docs.yml
.github/workflows/backend-deploy-dev.yml

- api 문서 배포 워크플로우에 추가 패스 지정
- 테스트 파일 내 docs디랙터리 내 파일 변경시 워크플로우 실행
- 기존에는 docs의 파일들이 변경되어야만 재배포가 되어 명세변경등으로 인한 테스트코드 변경시 배포가 안이뤄졌음
- workflow_dispatch 관련 조건 추가
- 기존 workflow_dispatch로 실행하는 워크플로우는 if condition을 없에 pr이 머지가 되지 않고 클로즈 되어도 실행
- 머지가 되거나, 워크플로우 디스패치 실행으로 워크플로우가 실행될 수 있도록 조견 변경

[BE] api 문서 배포 워크플로우 수정

---

.github/workflows/backend-deploy-dev-docs.yml

[BE] api문서 배포 워크플로우 실행 버튼 추가

---

frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
frontend/src/components/team/TeamExitModal/TeamExitModal.styled.ts
frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.styled.ts
frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.tsx
frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.stories.tsx
frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.styled.ts

> close #936 
전 후 사이즈 비교 
(왼쪽- 후 / 오른쪽 - 전)

[FE] 팀바팀 전반적인 모달 사이즈 조정

---

README.md

- readme 의 release뱃지가 최신 배포 태그를 자동으로 보이도록 수정

[ALL] readme release 뱃지 수정
