woowacourse-teams/2023-team-by-team

frontend/tsconfig.json

#5 
tsconfig의 속성 중 이제는 사용하지 않는 속성인 "skipDefaultLibCheck" 제거
https://typescript-kr.github.io/pages/compiler-options.html
https://www.typescriptlang.org/ko/tsconfig#skipDefaultLibCheck

[FE] 필요없는 타입설정 제거

---

backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
backend/src/test/resources/h2-data.sql

> #17 
- h2-data.sql에 스케쥴 테스트용 더미데이터 추가
- ScheduleRepository domain 패키지에 추가
- mysql 문법으로 data.sql에 작성했었는데, 문법 오류가 나서
- 따로 h2-data.sql에 h2 문법을 사용해서 테스트를 진행하기로 함.

[BE] 스케쥴 테스트용 더미데이터 추가

---

backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/ProfileImageUrl.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Span.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java

> #46 
- 몹 프로그래밍으로 도메인 작성 했던 것 중에서 @AllArgsConstructor, @NoArgsConstructor 누락됐던 거 추가 리팩토링
- `Member` 같은 경우는 필드 4개인데 Builder를 사용해야 할까? 생성자를 사용해야할까? (일단 @AllArgsConstructor 사용했음)
- `Span`은 이후에 시작 날짜가 끝 날짜보다 뒤인 경우 등 검증을 거칠 거라서 @AllArgsContructor 말고 이후에 직접 
검증 로직이 있는 생성자를 생성할 것 같은데, 일단 구현 전이니 `@AllArgsConstructor`를 사용했음.

[BE] refactor: @AllArgsConstructor & @NoArgsConstructor 추가 리팩토링

---

backend/src/main/java/team/teamby/teambyteam/global/exception/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleRegisterRequest.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Span.java
backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleException.java
backend/src/main/java/team/teamby/teambyteam/schedule/presentation/ScheduleController.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepository.java
backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceException.java
backend/src/test/java/team/teamby/teambyteam/fixtures/ScheduleFixtures.java
backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/domain/SpanTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepositoryTest.java

> #18 
- 일정 추가(등록) 기능 구현 
- Repository Test : commit(https://github.com/woowacourse-teams/2023-team-by-team/commit/e172724ff6939cf9527af023bbd559445f45dc33)
- Service Test : commit(https://github.com/woowacourse-teams/2023-team-by-team/commit/3c19012cc67744bf2bab113ddf0e2e0a2a9dc319)
- acceptance Test : commit(https://github.com/woowacourse-teams/2023-team-by-team/commit/4c17c936b9e0bb8b02e58ca196758e59a24ca435)
---
* Span에서 @AllArgsContructor 삭제, 모든 파라미터를 받는 생성자에 검증 로직 추가
* Request로 요청보낸 StartDateTime, EndDateTime의 형식도 검증한다.
* GlobalExceptionHandler 추가 (+ Handle 시 에러 로깅 추가)
* ScheduleFixtures 추가
* Repository 테스트 시 @DataJpaTest + @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
* ServiceTest 시 @nested로 공통 부분 (일정 등록) 추출
* 인수 테스트 예외 네이밍은 `실패한다`로 했음. (예외가 발생한다고 하면 …

[BE] 일정 추가 기능 구현

---

frontend/src/components/common/Text/Text.styled.ts

> close #75 
스타일 우선순위로 인해 h1 태그들의 스타일이 씹히는 현상을 발견,
대응가능한 태그 모두에게 적당한 스타일이 대응가능하도록 변경하고 cssprops의 우선순위를 높임.

[FE] h태그 및 cssProp 스타일 적용안되는 현상 fix

---

backend/.gitignore
backend/build.gradle
backend/src/docs/asciidoc/index.adoc
backend/src/docs/asciidoc/schedule.adoc
backend/src/test/java/team/teamby/teambyteam/schedule/docs/ScheduleApiDocsTest.java

> #81 
- 일정 추가 기능 문서화
> RestDocs 문서화 참고 자료
* Spring Rest Docs 공식 문서
https://docs.spring.io/spring-restdocs/docs/current/reference/htmlsingle/
* 우아한형제들 기술 블로그 - Spring Rest Docs 적용
https://techblog.woowahan.com/2597/
* 기타 블로그 - Spring REST Docs 적용 및 최적화하기 (굉장히 자세히 나와있음, 나중에 최적화도 이거 보고 할 수 있을듯?)
https://techblog.woowahan.com/2597/

[BE] 일정 추가 기능 문서화

---

frontend/.storybook/preview-head.html
frontend/public/index.html
frontend/src/styles/GlobalStyle.ts

> #83 
본 PR에서는 프론트엔드 프로젝트에 `Pretendard` 폰트를 추가하고, 기본 폰트로 `Pretendard` 가 적용되도록 글로벌 스타일을 수정하였다.
폰트를 적용하는 확장 프로그램 없이도 폰트가 스토리북에서 적용된 것을 확인할 수 있을 것이다.
- 이 폰트를 적용할 경우 굵은 폰트와 얇은 폰트 간의 차이가 두드러진다. `Text` 컴포넌트의 `font-weight` 를 필요에 따라 바꾸는 것을 고려해 보면 좋을 것 같다.

[FE] Pretendard 폰트를 추가하고, 기본 폰트로 적용되도록 수정

---

backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
backend/src/main/java/team/teamby/teambyteam/member/exception/MemberException.java

#29 
인터셉터 사용 경로: 모든 경로
보통 TokenProvider를 빈으로 만들어 토큰 생성(여기서는 상관 없음), 토큰 검증(이때 임의의 키가 들어감), PayLoad에서 필요한 부분 추출(이때도 임의의 키를 이용해 검증을 넣을 수 있음)을 담당하게 하는 것으로 보인다.
하지만 유효성 검증을 하지 않고 인터셉터를 구현하는 것을 목적으로 했기 때문에 내부 private 메서드로 필요 기능을 구현하였다.
1. 헤더에서 “Bearer “ 문자열 제거
2. 1에서 추출된 토큰에서 PayLoad를 분리하고 거기서 email 추출
3. email을 통해 Member를 조회하고 성공하면 정상, 실패하면 예외를 던지도록 구현
1. 요청할 때마다 MemberRepository를 조회하는 점
2. 커스텀 예외(현재 NotFoundException, IllegalTokenException을 만들어 적당한 때에 throw 중)

[BE] 멤버 인증 인터셉터 구현

---

.github/workflows/frontend-ci.yml
frontend/package.json

> close #91 
테스트 자동화 yml 스크립트 및 jest ci 테스트 명령어 작성

[FE] 테스트 자동화 yml 스크립트 및 jest ci 테스트 명령어 작성

---

frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
frontend/src/components/ScheduleAddModal/ScheduleAddModal.styled.ts
frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/common/Input/Input.stories.tsx
frontend/src/components/common/Input/Input.styled.ts
frontend/src/components/common/Input/Input.tsx

> #61 
본 PR에서는 팀 플레이스 캘린더에서의 일정 등록을 위한 모달의 UI를 구현하였다.
모달 밖을 클릭하거나 닫기 버튼을 누르면 모달이 닫히는 등의 기본적인 상호작용이 포함되어 있다.
- 스토리북
`YYYY-MM-DD` 형식으로 필드를 작성할 수 있도록 하기 위해 `<input type="date" />` 를 사용하여 구현했는데, `<input type="datetime-local" />` 을 사용하면 `YYYY-MM-DD HH:MM` 까지 설정할 수 있는 것 같아.
둘을 서로 비교해봐도 좋을 듯?
- `datetime-local`
코드가 많이 어지러운 편인데, 부디 바로잡아 줬으면 좋겠다. 많이 개선하면서 배울게...

[FE] 일정 등록 모달 UI 구현

---

backend/src/docs/asciidoc/schedule.adoc
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleUpdateRequest.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Span.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Title.java
backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleException.java
backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamPlaceScheduleController.java
backend/src/test/java/team/teamby/teambyteam/fixtures/ScheduleFixtures.java
backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/docs/ScheduleApiDocsTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepositoryTest.java

> #22 
- 일정 수정 기능 구현
- 일정 수정 문서화 
- 일정 수정 테스트 구현
- 대부분이 등록 기능, API 코드와 비슷하지만, 등록 코드에서 `ScheduleId`가 존재하지 않을 때 예외만 추가

[BE] 일정 수정 기능 구현

---

frontend/src/utils/generateScheduleBars.ts

> close #109
**본 PR에서는 캘린더가 오작동하고 불안정하게 작동하는 현상을 개선했다.**
여러 일정이 겹칠 경우 캘린더 바가 겹치지 않도록 서로 다른 높이에 랜더링되는데, 이를 **level** 이라 정의한다.
level 0의 경우 해당 캘린더 바가 해당 행의 최상단에 위치함을 의미하며, level이 1씩 증가할 수록 한 칸씩 아래에 위치함을 의미한다.
- 여러 주에 걸쳐 같은 일정의 캘린더 바가 랜더링 될 경우 서로 다른 level에 위치하는 문제점을 해결하였다.
- 현재 달에서의 일정의 범위를 일부분 벗어나는 경우, 혹은 아예 벗어나는 경우 오류를 발생시키지 않고 현재 달에 해당하는 일정에 한하여 일부분을 랜더링할 수 있도록 개선하였다.
- 일정의 시작 날짜가 끝 날짜보다 뒤에 오는 잘못된 입력이 주어질 경우 오류를 발생시키지 않고 해당 일정을 랜더링시키지 않도록 개선했다.
- 여러 주에 걸쳐 하나의 스케줄 바가 랜더링되어도 level이 유지된다.
- 여러 달에 걸쳐 스케줄 바를 랜더링할 수 있다.
- 잘못된 일정은 랜더링되지 않으며, 다른 스케줄 바의 level에 영향을 주지 않는다.

[FE] 캘린더 바 버그 수정 및 안정성 개선

---

frontend/.storybook/preview.tsx

> close #160 
본 PR에서는 스토리북의 `preview` 파일에 `@tanstack/react-query` 의 `QueryClientProvider` 를 추가하여 `react-query` 를 사용하는 컴포넌트들이 제대로 랜더링되지 않는 현상을 해결하였다.
- 발생했던 오류는 아래와 같다.

[FE] QueryClientProvider를 사용해서 컴포넌트가 스토리북에 제대로 보여지지 않는 문제 해결

---

frontend/src/utils/generateScheduleBars.test.ts

> close #162 
본 PR에서는 스케줄의 정보를 받으면 랜더링에 바로 사용할 수 있도록 가공된 형태의 스케줄 바를 반환하는 유틸함수에 대한 테스트 코드를 작성하였다.

[FE] 스케줄 바 유틸함수에 대한 테스트 코드 작성

---

frontend/src/components/Calendar/Calendar.tsx
frontend/src/hooks/queries/useFetchDailySchedules.ts
frontend/src/hooks/queries/useFetchSchedules.ts
frontend/src/utils/getDateByPosition.test.ts
frontend/src/utils/getDateByPosition.ts

> close #173 
본 PR에서는 년/월 정보, 그리고 캘린더의 좌표가 주어지면 이에 해당하는 날짜를 `Date` 객체로 반환하는 유틸 함수를 구현하였다.
- 예를 들어 `year = 2023`, `month = 6`, `row = 4`, `column = 3` 이라는 정보가 주어지면, 이 유틸함수는 `Wed Jul 26 2023 00:00:00 GMT+0900 (한국 표준시)` 값을 지니는 `Date` 객체를 반환한다.
이 유틸 함수는 스케줄 바에서의 행과 열의 정보를 바탕으로 날짜의 정보를 편리하게 받아오기 위해 사용될 예정이다.
프론트엔드에서 백엔드로 요청할 때는 월에 대한 정보를 우리가 알고 있는 월 그대로 요청하고 (7월이면 `7`), 프론트엔드 내부에서 월에 대한 정보를 다룰 때에는 1을 뺀 값을 사용하도록 (7월이면 `6`) 일관성을 지키기 위해 루루와 함께 일부 함수의 월 대입 로직을 변경하였다. 이슈 외의 내용이므로 추가 검토가 필요하다.

[FE] 좌표 날짜 변환 유틸함수 구현

---

backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java

#117
member interceptor 작동 경로를 /api/**로 경로설정, 인터셉터 내부에서 발생하는 예외를 global handler로 설정

[BE] member interceptor경로설정,인증예외설정

---

frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.tsx

> close #199 
유틸함수 이용해서 일정더보기를 누를 때 하루일정 모달이 뜨도록 함
위에서 3줄까지는 아래에 렌더링, 그 이후는 위에 렌더링

[FE] 일정더보기와 하루일정모달 연결

---

frontend/src/components/Notification/Notification.stories.ts
frontend/src/components/Notification/Notification.styled.ts
frontend/src/components/Notification/Notification.tsx
frontend/src/types/size.ts

> close #186 
모아보기 페이지에서는 sm 사이즈
팀 피드 페이지에서는 md(기본)사이즈
지금 팀플레이스 색상 영향을 받는 대부분의 컴포넌트가 위에서 color을 지정해주는 방식으로 하는데 어떻게 지정해서 보내줄지 슬슬 생각해보아야 할 것 같아요...

[FE] 팀 피드 일정 알림 컴포넌트 UI 구현

---

backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java

#195
일정 수정 & 삭제 시 해당 팀플레이스의 일정인지 검증 로직 추가

[BE] 일정 수정 & 삭제 시 해당 팀플레이스의 일정인지 검증 로직 추가

---

frontend/src/components/common/Menu/Menu.stories.tsx
frontend/src/components/common/Menu/Menu.tsx
frontend/src/components/common/Menu/MenuButton/MenuButton.tsx
frontend/src/components/common/Menu/MenuContext.tsx
frontend/src/components/common/Menu/MenuItem/MenuItem.styled.ts
frontend/src/components/common/Menu/MenuItem/MenuItem.tsx
frontend/src/components/common/Menu/MenuList/MenuList.styled.ts
frontend/src/components/common/Menu/MenuList/MenuList.tsx
frontend/src/hooks/useMenu.ts

> close #204
- Compound component 패턴을 적용하여 팀 플레이스, 시간대 선택 등 여러 파생 Menu로 재사용하기 용이하도록 개선
- 사용법은 Story를 보면 알 수 있습니다
[Vercel - Menu](https://vercel.com/design/menu)
[합성 컴포넌트로 재사용성 극대화하기](https://fe-developers.kakaoent.com/2022/220731-composition-component/)

[FE] 공통 Menu 컴포넌트 재사용성 개선

---

backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/ScheduleFixtures.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/domain/ScheduleRepositoryTest.java

> #231 
- ScheduleRepository 기존 쿼리 사용
```java
// ScheduleRepository
@Query("SELECT s FROM Schedule s " +
"WHERE s.teamPlaceId = :teamPlaceId " +
"AND s.span.startDateTime < :lastDateTime " +
"AND s.span.endDateTime >= :firstDateTime " +
"ORDER BY s.span.startDateTime ASC"
)
```
```java
// CalendarPeriod
public static CalendarPeriod of(final int year, final int month, final int day) {
LocalDate dailyDate = LocalDate.of(year, month, day);
LocalDate nextDay = dailyDate.plusDays(NEXT_DAY_OFFSET);
return new CalendarPeriod(LocalDateTime.of(dailyDate, START_TIME_OF_DAY), LocalDateTime.of(nextDay, START_TIME_OF_DAY));
}
}
```
- 7월 12일 하루 일정 조회 시
- firstDateTime : 2023-07-13 00:00:00 으로 DB Schedule의 startDateTime이 firstDateTime보다 이전인 경우 조건
- lastDateTime : 2023-07-12 00:00:00 으로 DB Schedule의 …

[BE] 팀 캘린더 하루 일정 조회 로직 리팩토링

---

backend/src/main/java/team/teamby/teambyteam/auth/presentation/TeamPlaceInterceptor.java
backend/src/main/java/team/teamby/teambyteam/auth/presentation/TeamPlaceParticipationInterceptor.java
backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberIdAndDisplayNameOnly.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberName.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/DisplayTeamPlaceName.java
backend/src/main/java/team/teamby/teambyteam/member/exception/MemberTeamPlaceException.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepositoryTest.java
backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceTest.java
backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberNameTest.java
backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayTeamPlaceNameTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java

> close #237 
- MemberTeamPlace 필드 추가
- DisplayMemberName
- DisplayTeamPlaceName
- MemberTeamPlace와 TeamPlace간 의존관계 단방향으로 변경
- MemberTeamPlace -> TeamPlace (n:1)
- 사용자가 요청을 보낸 팀플레이스 소속인지 확인하는 로직 변경
- 기존 : 팀플레이스 엔티티 사용
- 변경내용 : 멤버도메인 사용
- 해당 변경으로 없는 팀플레이스로의 요청시 예외 메시지 및 코드 변경 - 자세한 내용은 의논할 거리 확인
- TeamPlaceInterceptor의 이름을 더 직관적으로 변경
- 변경된 이름 : TeamPlaceParticipationInterceptor
- 멤버팀플레이스에서 사용자의 디스플레이네임과 아이디만 조회하는 repository method 구현
- @SproutMJ 이 작업중인 피드조회시에 확인해보고 필요한거 사용하면 될듯
기존에 멤버가 팀플레이스 소속인지 확인하던 방식
- 팀플레이스 엔티티에서 확인
수정후 사용할 방식
- 멤버 엔티티에서 확인
- 이유 : 팀플레이스 도메인에서 멤버팀플레이스 안가지고있음
생긴문제
- 없는 팀플레이스로 요청시
- 기존 : 없는 팀플레이스에 대한 요청이라는 오류 반환
- 변경후 : 접근할 수 없는 팀플레이스라는 오류 반환
해결방안
1. 소속확인 전에 팀플레이스 아이디로 있는지 확인한다.
- 장점 : 기존의 예외발생대로 처리를 할 수 있다.
- 단점 : 리팩터링을 진행함으로 팀플레이스에 대한 쿼리를 안날려도 되도록 조회 요청 횟수가 줄게되었는데, 다시 …

[BE] Member, MemberTeamPlace, TeamPlace 구조 및 연관관계 리팩터링

---

frontend/src/assets/svg/check.svg
frontend/src/assets/svg/index.ts
frontend/src/components/common/Checkbox/Checkbox.stories.tsx
frontend/src/components/common/Checkbox/Checkbox.styled.ts
frontend/src/components/common/Checkbox/Checkbox.tsx
frontend/src/types/size.ts

> close #172
본 PR에서는 공용 체크박스를 구현하였다.
- 체크박스는 state를 가지지 않으며, 체크박스가 체크되어 있는지의 여부인 `isChecked` 와 `onChange` 를 통한 트리거를 제공한다.
- 즉, 이 컴포넌트를 사용할 경우 state를 사용하는 측에서 별도로 관리하게 된다.
- 체크박스의 사이즈는 `sm`, `md`, `lg`, `xl` 각각 `20px`, `26px`, `32px`, `38px` 이며, 이중 `md` 사이즈는 일정 생성 모달에서 쓰이는 사이즈와 `1px` 가량 차이난다.
- 체크박스 자체에 `state` 를 넣는 것이 좋을까? 체크박스 리스트처럼 여러 개의 체크박스를 한꺼번에 관리할 때는 어떻게 해야 하지?

[FE] 공통 체크박스 컴포넌트 구현

---

frontend/src/components/common/Menu/MenuItem/MenuItem.tsx

> 사소한 버그픽스라 이슈 제외
MenuItem의 css prop optional로 수정

[FE] MenuItem의 css prop optional로 수정

---

frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/hooks/schedule/useScheduleAddModal.ts
frontend/src/hooks/useCalendar.ts

> close #147 
- 일정 등록 모달의 기본 날짜 변경
- 클릭된 DateCell의 요일을 받아오도록 수정
- input의 type을 date로 수정

[FE] 일정 등록 모달 기본 날짜 변경

---

frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.stories.tsx
frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
frontend/src/hooks/useBottomSheet.ts
frontend/src/styles/theme.ts

> close #182 
- 팀피드 스레드 작성 바텀시트 구현
- UI만 구현
- css animation을 theme에 추가

[FE] 팀피드 스레드 작성 바텀시트 구현

---

frontend/src/components/ScheduleAddModal/ScheduleAddModal.styled.ts
frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/ScheduleEditModal/ScheduleEditModal.styled.ts
frontend/src/components/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/ScheduleModal/ScheduleModal.styled.ts
frontend/src/components/ScheduleModal/ScheduleModal.tsx
frontend/src/components/common/Header/Header.styled.ts
frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/TeamBadge/TeamBadge.stories.ts
frontend/src/components/common/TeamBadge/TeamBadge.styled.ts
frontend/src/components/common/TeamBadge/TeamBadge.tsx
frontend/src/styles/theme.ts
frontend/src/types/size.ts
frontend/src/types/team.ts

> close #261 
teamPlaceColor랑 teamColor 는 지금 필요해서 해둔거고 하루일정UI 에 있는거랑 똑같은거에요..

[FE] 공용 컴포넌트 team badge 구현

---

.github/workflows/frontend-ci.yml

- 빌드 실패 시 action이 실패하도록 CI 스크립트 수정
- 배포 직전에 확인하는 과정이 불편하여, CI 과정에 추가

[FE] 빌드 실패 시 action이 실패하도록 CI 스크립트 수정

---

frontend/src/constants/calendar.ts
frontend/src/types/schedule.ts
frontend/src/utils/generateScheduleCirclesMatrix.test.ts
frontend/src/utils/generateScheduleCirclesMatrix.ts

> close #256
본 PR에서는 통합 캘린더를 랜더링할 때 스케줄 서클을 어디에 랜더링해야 하는지를 알 수 있는 유틸 함수를 구현하였다.
- 스케줄 서클이란, 통합 캘린더에서 여러 팀의 일정을 축약하여 표시하기 위한 원들을 의미한다.
입력으로 `teamPlaceId` 정보가 포함된 `schedule[]` 을 받으며 (`scheduleWithTeamPlaceId[]`), 아래의 형태로 결과를 반환한다.
```tsx
{
teamPlaceId: number[]
}[][] // 6행 7열의 2차원 배열
```

[FE] 통합 캘린더 스케줄 서클 구현을 위한 유틸 함수 작성

---

frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/ScheduleEditModal/ScheduleEditModal.styled.ts
frontend/src/components/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/TimeTableMenu/TimeTableMenu.stories.tsx
frontend/src/components/TimeTableMenu/TimeTableMenu.styled.ts
frontend/src/components/TimeTableMenu/TimeTableMenu.tsx
frontend/src/components/common/Menu/Menu.stories.tsx
frontend/src/components/common/Menu/Menu.tsx
frontend/src/hooks/schedule/useScheduleEditModal.ts

> close #168
- 일정 수정 종일/시간대 선택 구현
- 일정 등록과 로직이 유사함
- 종일 일정인 경우 체크된 상태로 보여주고, 체크 해제 시 마감 시간은 23:30
- 시간대 선택 메뉴를 TimeTableMenu 컴포넌트로 분리

[FE] 일정 수정 종일/시간대 선택 구현

---

frontend/src/components/MyCalendar/MyCalendar.styled.ts
frontend/src/components/MyCalendar/MyCalendar.tsx
frontend/src/components/common/TeamBadge/TeamBadge.styled.ts
frontend/src/hooks/queries/useDeleteSchedule.ts
frontend/src/hooks/queries/useModifySchedule.ts
frontend/src/hooks/queries/useSendSchedule.ts
frontend/src/mocks/handlers/calendar.ts

[FE]통합캘린더 스케줄 렌더링 
> close #274 
스케줄 등록/수정/삭제에 의존성 추가
스케줄 msw에 야매로 통합도 반영되도록 함. 
통합이랑 스케줄이랑 data가 달라서 안에 있는지 없는지는 검사안하고 있음-> 새로 등록 하고 삭제 하는 것에 대해서만 msw통해서 통합 캘린더 볼 수 있음

[FE]통합캘린더 스케줄 렌더링

---

frontend/src/components/ScheduleModal/ScheduleModal.tsx
frontend/src/hooks/schedule/useScheduleAddModal.ts
frontend/src/hooks/schedule/useScheduleEditModal.ts

> close #272 
- 일정 등록, 수정, 삭제 성공 시 Toast를 보여주는 로직 추가

[FE] 일정 등록, 수정, 삭제 성공 시 Toast를 보여주는 로직 추가

---

frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
frontend/src/components/ScheduleBar/ScheduleBar.tsx

> close #180 
- 스케줄바 타이틀 표시 구현

[FE] 스케줄바 타이틀 표시 구현

---

frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
frontend/src/components/ScheduleBar/ScheduleBar.tsx
frontend/src/utils/generateScheduleBars.test.ts
frontend/src/utils/generateScheduleBars.ts

> close #291
본 PR에서는 `<ScheduleBar>` 에 `schedule` props 를 추가하였다.
이는 스케줄 바 내부에서 스케줄에 대한 정보가 필요할 때 fetch를 하지 않고 받아온 정보를 그대로 활용할 수 있도록 하기 위함이다.
리팩터링 이후의 `ScheduleBarProps` 타입은 아래와 같다.
```tsx
export interface ScheduleBarProps {
id: string;
scheduleId: number;
schedule: Schedule;
title: string;
row: number;
column: number;
duration: number;
level: number;
color?: string;
onClick?: () => void;
}
```

[FE] 스케줄 바에 schedule prop 추가 및 유틸함수 리팩터링

---

frontend/src/apis/team.ts
frontend/src/hooks/queries/useFetchTeamPlaces.ts
frontend/src/mocks/fixtures/team.ts
frontend/src/mocks/handlers/index.ts
frontend/src/mocks/handlers/team.ts
frontend/src/types/team.ts

> close #275 
본 PR에서는 팀 정보를 조회해 올 수 있도록 비동기 로직을 구현하였다. 팀 정보 조회에 대한 msw 모킹이 포함되어 있다.

[FE] 팀 정보를 조회해오는 API 로직 구현

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedType.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/ScheduleNotification.java
backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
backend/src/test/java/team/teamby/teambyteam/feed/application/NotificationServiceTest.java

#307
조회 타입을 SCHEDULE_NOTIFICATION->NOTIFICATION으로 변경하고 반환 타입을 전부 소문자로 하도록 변경

[BE] 스레드 조회 타입 수정

---

backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeResponse.java
backend/src/main/java/team/teamby/teambyteam/notice/domain/NoticeRepository.java
backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/NoticeFixtures.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/NoticeAcceptanceFixtures.java
backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
backend/src/test/java/team/teamby/teambyteam/notice/domain/NoticeRepositoryTest.java

> #218 
- 공지 조회 기능 구현
- (공지 기등록 시) 가장 최근에 등록된 공지 조회
- (공지 미등록 시) 빈값 반한
- 공지 조회 기능 관련 레포지토리, 서비스, 인수 테스트 구현

[BE] 공지 조회 기능 구현

---

backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
backend/src/main/java/team/teamby/teambyteam/member/application/dto/TeamPlaceResponse.java
backend/src/main/java/team/teamby/teambyteam/member/application/dto/TeamPlacesResponse.java
backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
backend/src/main/java/team/teamby/teambyteam/member/domain/TeamPlaceColor.java
backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/TeamPlaceFixtures.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTest.java

> close #287
- Member가 TeamPlace에 소속되는 domain 기능 구현
- 사용자가 속한 팀플레이스들의 목록 조회 기능 구현
- 소속된 팀플레이스가 없을 경우 빈 리스트 반환
meerge전에 db서버 table 스키마 변경 ( member_team_palce table -> team_place_coler 추가 : 노션 ddl참고)

[BE] 사용자가 속한 팀플레이스들 목록 조회 기능 구현

---

frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/MyCalendar/MyCalendar.stories.tsx
frontend/src/components/MyCalendar/MyCalendar.tsx
frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.stories.ts
frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.tsx
frontend/src/components/Notification/Notification.stories.ts
frontend/src/components/Notification/Notification.styled.ts
frontend/src/components/Notification/Notification.tsx
frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
frontend/src/components/ScheduleBar/ScheduleBar.tsx
frontend/src/components/ScheduleEditModal/ScheduleEditModal.stories.tsx
frontend/src/components/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/ScheduleModal/ScheduleModal.tsx
frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.styled.ts
frontend/src/components/ThreadList/ThreadList.tsx
frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/SideBar/SideBar.tsx
frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.styled.ts
frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.tsx
frontend/src/contexts/TeamPlaceContext.tsx
frontend/src/hooks/useTeamPlace.ts
frontend/src/index.tsx
frontend/src/types/schedule.ts
frontend/src/utils/generateScheduleBars.test.ts
frontend/src/utils/generateScheduleBars.ts
frontend/src/utils/getInfoByTeamPlaceId.ts

>close #308 #114 
캘린더 페이지 간단한 반응형 적용 (paading)
일정 더보기 간단한 반응형 적용
팀플레이스 아이디에 따라 보여주는 정보 다르게 함
- 스케줄바
- 스케줄 모달, 추가모달, 수정모달
- 헤더의 팀 정보
- 스레드의 일정알림 색상
- 통합 캘린더
계속 teamplace 정보 fetch하는게 불안정하다고 생각 + 어차피 한번에 보여줘야하는 부분
의 이유로 context로 만들어 감쌌습니다. 
나중에 페이지 param으로 팀플레이스 id 추출할 수 있게된다면 로직을 합칠 수 있을 것 같습니다.

[FE] 팀플레이스 색상과 조회 로직 연결

---

frontend/src/utils/generateScheduleCirclesMatrix.test.ts
frontend/src/utils/generateScheduleCirclesMatrix.ts

> close #310 
본 PR에서는 스케줄 서클을 어떻게 랜더링해야 하는지를 반환하는 유틸 함수에서 캘린더의 각 셀에 여러 개의 팀플레이스 아이디가 잘못 반환되는 현상을 해결하였다.
셀에 랜더링되어야 하는 스케줄 서클의 팀플레이스 아이디들이 `[1, 2, 7, 2, 11, 2, 7]` 인 경우, 실제로는 `[1, 2, 7]` 의 형태로 반환되어 랜더링되어야 하는 것이다 (중복을 제거하고, 오름차순 정렬을 진행한 후, 팀플레이스 아이디를 최대 앞에서부터 세 개까지만 반환)

[FE] 스케줄 서클 유틸함수 중복반환 해결

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java

#317
스레드 조회 시 소속 팀플레이스의 이름으로 조회되도록 변경

[BE] feed thread 조회 시 MemberTeamPlace의 DisplayMemberName으로 조회되도록 변경

---

frontend/src/components/Calendar/Calendar.tsx
frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/Input/Input.tsx
frontend/src/components/common/Menu/MenuList/MenuList.tsx
frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
frontend/src/components/common/NavigationBar/NavigationBar.tsx
frontend/src/components/common/Toast/Toast.tsx
frontend/src/styles/GlobalStyle.ts

> close #322
본 PR에서는 사용자가 팀 캘린더 페이지에 접속하고, 새로운 일정을 생성하기까지의 과정의 웹 접근성을 개선하였다.
- 키보드만을 이용하여 메뉴를 자유로이 이동하고, 새로운 일정을 생성할 수 있다.
- 일정 등록 메뉴 / 팀 피드 메뉴를 편리하게 이용할 수 있도록, 모달을 열었을 때 자동으로 인풋에 포커스를 준다.
- 스크린 리더만으로 어떠한 작업이 진행되는지를 충분히 알 수 있도록 구현하였다. 다만 커스텀 메뉴 컴포넌트 (시간 선택 인풋)에 한해서는 이를 개선하지 못했다.

[FE] 일정 등록 접근성 개선

---

frontend/src/components/pages/FeedPage/FeedPage.styled.ts
frontend/src/components/pages/FeedPage/FeedPage.tsx

[FE] 바텀시트가 화면 하단에 고정되지 않는 현상 수정

---

backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeResponse.java
backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java

> #324 
- 공지 조회 시 등록자명 표시 방식 변경(Member의 이름 -> MemberTeamPlace의 DisplayName)
- 관련 테스트 수정
- PostMan Test

[BE] 팀 공지 조회 시 member team place의 display name이 조회되도록 기능 변경

---

backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberArgumentResolver.java
backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java

> #364 
- MemberArgumentResolver에서 JwtTokenProvider 사용하도록 리팩토링
- 기존 JsonParser 사용 시 RestDocsTest에서 MockBean이 제대로 안되는 문제가 발생함.
- 이미 있는 로직인 JwtTokenProvider의 extractEmailFromToken을 재사용하고, RestDocs에서 jwtTokenProvider를 MockBean하기 위해 리팩토링

[BE] MemberArgumentResolver에서 JwtTokenProvider 사용하도록 리팩토링

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberIdAndDisplayNameOnly.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeResponse.java
backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepositoryTest.java

> close #367 
- MemberTeamPlace에서 Projection 제거
- 제거 이유
- 기존에는 사용자의 displayname과 id만 가져옴
- 피드등의 조회 api에서 diplayNmae, id 뿐만 아니라 profile image url도 필요
- 해당 필드는 member entity에만 있음
- projection사용시 member는 memberRepository를 통해 다시 가져와야함
- entity를 가져와서 memberTeamPlace에서 member를 가져와 사용할 수 있도록 변경

[BE] MemberTeamPlaceRepository 반환데이터 변경

---

backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceCreateRequest.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceCreateResponse.java
backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamPlaceAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java

> close #321
- 팀플레이스 생성 api 구현
- 팀플레이스 생성시 요청한 멤버는 해당 팀플레이스에 자동 소속

[BE] 팀플래이스 생성 api. 구현

---

frontend/src/App.tsx
frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
frontend/src/components/common/Text/Text.styled.ts
frontend/src/components/common/Text/Text.tsx
frontend/src/constants/routes.tsx
frontend/src/contexts/TeamPlaceContext.tsx
frontend/src/hooks/queries/useFetchTeamPlaces.ts
frontend/src/pages/CreatePage/CreatePage.styled.ts
frontend/src/pages/CreatePage/CreatePage.tsx
frontend/src/pages/JoinPage/JoinPage.styled.tsx
frontend/src/pages/JoinPage/JoinPage.tsx
frontend/src/pages/LandingPage/LandingPage.tsx
frontend/src/pages/LoginPage/LoginPage.tsx
frontend/src/pages/PageTemplate/PageTemplate.tsx
frontend/src/pages/StartPage/StartPage.styled.ts
frontend/src/pages/StartPage/StartPage.tsx
frontend/src/styles/theme.ts

> close #395 
로그인 시 팀이 없으면 자동으로 /start로 이동
><이전 flow>
로그인 페이지에서 "토큰" 을 획득
/team 으로 이동
/team 에서 백엔드에 소속 팀 정보를 요청하고, 요청 결과에 따라 적합한 페이지로 이동 = 페이지 여러 번 이동해서 버벅거림, 뒤로가기 시 원치 않는 사이트로 이동할 수 있음
<바꾼 로직>
/login 에서 토큰을 받은 이후 팀 정보도 요청 -> 리다이렉트 시키기 전 우리가 팀 소속여부를 알 수 있음
<현재 flow>
로그인 페이지에서 "토큰" 을 획득하고, 이후 비동기 요청을 보내 "팀 정보" 도 획득
토큰과 팀 정보를 통틀어서 다음 페이지로 어떻게 이동할지를 정하고, 이동 = 페이지 여러 번 이동할 필요 없음, 뒤로가기 시 예상했던 페이지로 이동
/landing 에서 accessToken과 teamPlaceId 둘 다 있을 시만 자동 로그인 되도록 변경
teamPlaceProvider에서 teamPlaces 패치가 끝난 후, local에 있으면 해당 팀 id 초기값으로, 없으면 팀 중 가장 먼저팀 id 를 초기값으로 정하도록 변경
local에 access 넣고 /start로 가서 확인해주시면 됩니당

[FE]팀 참가, 생성 페이지 구현

---

backend/src/main/java/team/teamby/teambyteam/auth/presentation/TeamPlaceParticipationInterceptor.java
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceParticipantResponse.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceInviteCodeRepository.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/vo/InviteCode.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceInviteCodeRepositoryTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/domain/vo/InviteCodeTest.java

#284 
멤버 정보와 초대코드를 이용해 팀플레이스를 가입한다.
이미 가입한 상태에서 재요청을 하는 경우 반환값은 동일하다.
없는 초대코드를 사용하는 경우 404를 반환한다.
잘못된 길이(!=8)의 초대코드로 요청하는 경우 400을 반환한다.

[BE] 팀플레이스 가입 구현

---

backend/src/test/java/team/teamby/teambyteam/common/ApiDocsTest.java

> #418 
문서화 공통 클래스 ApiDocsTest 구현
* JpaMetamodelMappingContext MockBean은 JPA Auditing(BaseEntity) 관련 기능이어서 MockBean
* MemberInterceptor, teamPlaceParticipationInterceptor는 모두 통과하도록 @BeforeEach 설정
* 상속받는 문서화 클래스에서 사용하기 위해 접근 제어자 protected 처리
---
**각각의 Controller, Service는 문서화 테스트 클래스 내에서 @WebMvcTest, @MockBean으로 선언해서 사용!**
-> 안하면 빈 주입 오류나므로 꼭 매 테스트 마다 잊지말고 하기

[BE] 문서화 공통 클래스 ApiDocsTest 구현

---

backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceCreateRequest.java
backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java

기존 : 팀플레이스 생성시 잘못된 이름 요청에 500 예외 발생
수정 : 팀플레이스 생성요청시 공백, 31자이상등의 입력에서 404 예외 발생으로 변경

[BE] 팀플레이스 생성 요청시 예외 코드 오류 수정

---

frontend/src/pages/CreatePage/CreatePage.tsx
frontend/src/pages/JoinPage/JoinPage.tsx
frontend/src/pages/StartPage/StartPage.tsx

> close #436
본 PR에서는 아래 3개의 메뉴에 대해 랜딩 페이지에 구현된 장식 컴포넌트를 적용하였다.
애니메이션은 비활성화 되어 있다.
- 팀 생성 페이지 - `/create`
- 팀 참가 페이지 - `/join`
- 팀 생성/참가 선택 페이지 - `/start`

[FE] 랜딩 페이지의 장식 컴포넌트를 3개의 메뉴에도 적용

---

backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java

> close #452 
- 공지 작성자 조회시 해당 팀플레이스와 작성자 아이디로 조회하도록 수정
- 관련 테스트 추가

[BE] 공지 작성자 표기 오류 수정

---

backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
backend/src/main/java/team/teamby/teambyteam/member/application/dto/MemberInfoResponse.java
backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java

> close #450
- 로그인한 사용자가 내 정보를 조회하는 기능 구현
- 인증된 사용자의 요청시 응답 body와 함께 200 응답
- 인증되지 않은 사용자의 요청시 401 응답

[BE] 내정보 조회 API 구현

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/dto/TokenResponse.java
backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java

> #464 
- 구글 로그인 시 리프레시 토큰도 발급하도록 리팩토링
- 테스트는 외부 API 테스트라 Mocking 해야해서 시간이 좀 걸려서 급하므로 이전에 이슈 생성해놨음 (테스트 하기 이슈)

[BE] 구글 로그인 시 리프레시 토큰도 발급하도록 리팩토링

---

frontend/.storybook/preview.tsx

> close #476 
본 PR에서는 `<BrowserRouter>` 를 스토리북의 데코레이터에 추가하여, 라우터가 요구되는 컴포넌트들이 오류가 발생하면서 랜더링이 되지 못 했던 문제를 해결하였다.

[FE] 라우터가 요구되는 컴포넌트를 스토리북에서 확인할 수 있도록 스토리북에 라우터를 추가

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java

> 긴급으로, 이슈 X
- `/code/google`로 로그인 요청 들어왔을 시, 응답으로 RefreshToken QueryParameter에 Key-Value로 넣었음
- 이때, QueryParameter에 생성한 RefreshToken을 넣기 전, Service에서 DB에 먼저 토큰을 저장하지 않음.
-> 이후에 토큰 재발급 시 QueryParameter에 발급한 토큰을 DB에 넣지 않았으므로 토큰을 찾을 수 없다는 버그 발생
- GoogleOAuthService의 createToken()에서 토큰을 생성하고, DB에 저장하도록 리팩토링
- 이 과정에서, Token Entity를 생성하기 위해 영속화된 Member가 필요했음.
- 기존에 createMemberIfNotExist()에서는 exist 쿼리로 Email에 해당하는 멤버가 존재하면 Early Return 했지만,
- Email에 해당하는 멤버가 존재하면 해당 멤버를 반환해야 했음 
- 그래서 findByEmail로 Optional<Member>를 받아서 처리했음.

[BE] 리프레시 토큰 발급 시 DB 저장하도록 버그 fix

---

backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
backend/src/main/java/team/teamby/teambyteam/token/application/TokenService.java
backend/src/main/java/team/teamby/teambyteam/token/domain/TokenRepository.java
backend/src/main/java/team/teamby/teambyteam/token/exception/TokenException.java
backend/src/test/java/team/teamby/teambyteam/token/acceptance/TokenAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/token/application/TokenServiceTest.java

기존 문제 : Refresh token의 정보가 db에 있는 멤버의 로그인 요청시 오류 발생
원인 : token table의 member_id가 unique 값이여서 기존에 해당 유무를 검증하지 않고 save하여 오류 발생
해결 : 회원로그인시 refresh token가 저장되어있는지 유무에 따라 저장 또는 기존 토큰 업데이트

[BE] 리프레시 토큰이 db에 있는 사용자의 재 로그인시 오류 수정

---

frontend/src/App.tsx
frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/NavigationBar/NavigationBar.tsx
frontend/src/components/feed/ThreadList/ThreadList.tsx
frontend/src/components/link/LinkTable/LinkTable.tsx
frontend/src/constants/routes.tsx
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
frontend/src/pages/TeamOverviewPage/TeamOverviewPage.styled.ts
frontend/src/pages/TeamOverviewPage/TeamOverviewPage.tsx
frontend/src/pages/TeamSelectPage/TeamSelectPage.tsx

> close #482
본 PR에서는 모아보기 페이지를 구현하였다.
고도화 및 디자인은 적용되어 있지 않으므로 추후 고도화를 원할 경우에는 따로 작업을 하도록 한다.
페이지명은 `TeamOverviewPage`, 도메인 주소는 `/team/overview` 이다.
- 요술토끼의 노트북 화면에서 본 모아보기 페이지
- 요술토끼의 데스크톱 모니터에서 본 모아보기 페이지
생각보다 각각의 메뉴(팀 피드 / 팀 캘린더 / 팀 링크) 가 너무 큰 것 같은데...? 괜찮으려나? 어떻게 하면 좋을까

[FE] 모아보기 페이지 구현

---

frontend/src/components/feed/ThreadList/ThreadList.tsx

> close #517 
- 스레드 무한 스크롤 fetchNextPage에 teamPlaceId 판별 조건문 추가

[FE] 스레드 무한 스크롤 fetchNextPage에 teamPlaceId 판별 조건문 추가

---

frontend/src/components/link/LinkTable/LinkTable.tsx
frontend/src/hooks/link/useTeamLinkAddModal.ts
frontend/src/utils/ensureHttpsPrefix.ts
frontend/src/utils/generateHttpsUrl.ts

> close #525 
본 PR에서는 일부 링크에 한해 클릭 시 사용자가 입력한 주소가 아닌 팀바팀 내의 상대주소로 인식하여 잘못 이동하는 문제를 해결하였다.
- 사용자가 `https://` 또는 `http://` 로 시작하지 않는 주소를 입력했으면서, 그 주소가 유효하면 자동으로 `https://` 를 앞에 붙여 서버에 요청한다.
- 서버로부터 받아온 링크가 `https://` 또는 `http://` 로 시작하지 않는 경우, 자동으로 `https://` 를 앞에 붙인 후 랜더링한다.

[FE] 팀 링크에서 https:// 로 시작하지 않는 경우 잘못된 주소로 이동하는 문제 해결

---

frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
frontend/src/components/link/LinkTable/LinkTable.tsx
frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.styled.ts
frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.tsx
frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx

> close #151 #531
모아보기 페이지에서 모달들의 위치의 각 도메인별 영역으로 고정했습니다.
캘린더의 일정 등록 수정 조회, 하루조회 모달은 클릭한 위치에 상관없이 고정됩니다.
요토의 PR과 합쳐야 합니다. 또한 제 PR에서 캘린더 페이지의 모달 위치는 요토 PR 과 합치기 위해 상수 박아둔거라 이상하게 보일 가능성이 큽니다. 모아보기 페이지 모달만 확인하면 됩니다.

[FE] 모아보기 페이지 모달 UI 개선

---

.github/workflows/deploy-prod-latest.yml

- Release 생성시 운영서버 배포 워크플로우에 해당 release가 main브랜치에서 생성된 것인지 확인 추가
[공식문서](https://docs.github.com/en/free-pro-team@latest/rest/releases/releases?apiVersion=2022-11-28#list-releases)
[stack over flow link](https://stackoverflow.com/questions/71083657/trigger-github-workflow-only-on-the-release-tag-event-and-specific-path)

[ALL] main 브렌치 발생 release만 배포

---

frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.styled.ts
frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.tsx

[FE] 팀 이름이 길면 선택칸 보다 넘치는 버그 수정

---

backend/src/main/java/team/teamby/teambyteam/auth/exception/AuthenticationException.java
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java

#563 
500 에러 로깅을 위한 코드입니다.
HttpMessageNotReadableException: 일정 수정 시 json 에러를 잡는다. 
예시) 10:10이 아니라 10-10 
발생위치 추정: @RequestBody 
DateTimeException: 기간 요청에 잘못된 형식으로 요청하는 경우 
예시) -1월 
발생 위치 추정: Service 계층 
MethodArgumentTypeMismatchException: 기간 요쳥에 잘못된 형식으로 요쳥하는 경우 
예시)y2023 
발생 위치 추정: @RequestParam

[BE] 500 에러 로깅용 코드 작성(에러 메시지 반환은 하지 않음)

---

backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java

- Runtime Exception시 생성되는 예외 로그 레벨 error로 변경
- 해당 예외는 우리가 처리하지 못한 예외여서 warn이 아닌 error로 로깅이 되는것이 더 적합하다고 판단하여 수정했습니다.
- 예외메시지 로깅 및 출력시 예외 키값 추가
- 사용자에게 예외발생에 대한 문의시 어떠한 오류인지 로그 트레이싱이 쉽도록 예외키값 추가
- 사용자가 요청한 시간 또는 날짜를 추정할 수 있어서 모든 로깅에 대해서 unique한 값을 보장할 필요가 없다고 판단

[BE] 예외상황시 발생로그 레벨 변경

---

backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMemberResponse.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMembersResponse.java
backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java

> close #592
- 소속된 팀의 팀원 조회시 본인 여부 필드 추가
- 필드명 : `isMe`

[BE] 소속된 팀의 팀원 조회시 본인 여부 필드 추가

---

backend/src/docs/asciidoc/teamPlace.adoc
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/domain/TeamPlaceColor.java
backend/src/main/java/team/teamby/teambyteam/member/exception/MemberTeamPlaceException.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceChangeColorRequest.java
backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamPlaceAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/member/domain/TeamPlaceColorTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/docs/TeamPlaceControlApiDocsTest.java

> close #588 #589 
- 팀 플레이스 색상 변경 기능 / 문서화 구현
- `TeamPlaceColor` ENUM에서 ColorNumber에 해당하는 색상 찾아서 반환하는 기능 추가
-  색상 번호에 해당하는 TeamPlaceColor가 없다면 커스텀 예외 발생해서 Handler에서 400으로 처리하도록 구현
- API URI가 `/api/team-places/{teamPlaceId}/color` 이므로 TeamPlaceController가 존재하는 TeamPlace 패키지(TeamPlaceService)에서 구현

[BE] 팀플레이스 색상 변경 기능 / 문서화 구현

---

backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberName.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/DisplayMemberNameChangeRequest.java
backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMemberResponse.java
backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamPlaceAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberNameTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java

> close #593
- 팀 내에서 보일 내 별명 수정 기능 추가
- 팀플래이스 참여자들 정보 조회시 displayName이 아닌 사용자 기본 이름이 조회되는 오류 수정

[BE] 팀플래이스에서 보일 내 별명 변경 기능 구현

---

backend/src/docs/asciidoc/member.adoc
backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
backend/src/test/java/team/teamby/teambyteam/member/docs/MemberApiDocsTest.java

#591 
회원 탈퇴 api
회원 없을 시 404 에러
회원 탈퇴 시 팀플레이스 모두 탈퇴
회원 탈퇴시 즉시 회원 정보 삭제(기타 기록은 삭제되지 않음)

[BE] 회원 탈퇴 api 구현

---

.github/CODEOWNERS

본 PR에서는 잘못된 CODEOWNERS 파일을 올바르게 수정하였다.
- 문법이 잘못된 것은 아니지만, 범위가 잘못되어 해당 분야의 파일이 변경되었을 때 **하위** 파일이 변경되면 성공적으로 리뷰어가 배정되지만 **하위의 하위** 파일이 변경되었을 때 리뷰어가 배정되지 않는 문제가 있었다.
- 이에 경로 범위를 `/frontend/*` 에서 `/frontend/` 와 같이 변경하였다.
`CODEOWNERS` 파일에서, `/path/*` 와 `/path/` 가 의미하는 바가 다른데,
- `/path/*` 는 `/path/` 경로의 **직접적인 하위 파일** 들만 해당해. `/path/abcd.txt` 는 해당하지만 `/path/path2/abcd.txt` 는 해당되지 않음.
- `/path/` 는 `/path/` 경로의 **모든 depth의 하위 파일** 들이 모두 해당돼. `/path/abcd.txt` 는 물론 `/path/path2/abcd.txt` 또한 해당됨.
이러한 차이가 있는듯.

[ALL] 잘못된 CODEOWNERS 파일 수정

---

backend/src/main/java/team/teamby/teambyteam/auth/exception/AuthenticationException.java
backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenExtractor.java
backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenProvider.java
backend/src/main/java/team/teamby/teambyteam/auth/presentation/MemberInterceptor.java
backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/test/java/team/teamby/teambyteam/auth/jwt/JwtTokenProviderTest.java
backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/member/docs/MemberApiDocsTest.java
backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/sharedlink/docs/SharedLinkApiDocsTest.java
backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/token/application/TokenServiceTest.java
backend/src/test/java/team/teamby/teambyteam/token/docs/TokenApiDocsTest.java

* MemberInterceptor 예외 401로 변경 + 인증 예외 로깅 리팩토링
* MemberInterceptor 404 -> 401로 변경
* 모든 인증 예외 : '인증이 실패했습니다.' 로깅이었던 것 -> 로깅 정보 추가해서 로깅되도록 수정
* AuthenticationException에서 message로 logMessage를 받아서 Handler에서 로깅 시 사용하도록 리팩토링
* 사용자에게 나갈 ErrorResponse는 Handler에서 직접 설정("인증이 실패했습니다.")

[BE] MemberInterceptor 예외 401로 변경 + 인증 예외 로깅 리팩토링

---

backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
backend/src/main/java/team/teamby/teambyteam/member/configuration/dto/MemberUpdateRequest.java
backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java
backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
backend/src/test/java/team/teamby/teambyteam/member/domain/vo/NameTest.java

> #595 
- 회원의 본인 정보(이름) 수정 기능 구현 및 테스트
- 회원의 변경 전 이름과 DisplayName 일치 시 -> DisplayName을 새로운 이름으로 변경
- 회원명의 앞뒤에 공백이 있을 경우 해당 공백을 제거(Trim)
- member 이름과 DisplayName의 일치할 경우 DisplayName을 변경하는 로직에서 indent Depth가 2임
```
for (final MemberTeamPlace memberTeamPlace : memberTeamPlaces) {
if (memberTeamPlace.getDisplayMemberName().getValue().equals(member.getName().getValue())) {
memberTeamPlace.changeDisplayMemberName(new DisplayMemberName(memberUpdateRequest.name()));
}
}
```
- stream 사용할 경우 foreach로 메서드를 실행해야하는 문제가 있어 적용의 어려움 발생
- 해당 코드를 리팩터링 할 방법이 있을지?

[BE] 회원정보 수정 기능 구현

---

frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
frontend/src/hooks/queries/usePrefetchSchedules.ts

> close #586 
- 이전 달과 다음 달의 데이터를 미리 불러오는 기능 구현
https://tanstack.com/query/v4/docs/react/guides/prefetching
- Prefetching으로 문제가 해결되는지 아직 알 수 없으므로 개발 서버 배포 후 확인 필요함

[FE] 이전 달과 다음 달의 데이터를 미리 불러오는 기능 구현

---

frontend/src/apis/http.ts
frontend/src/apis/team.ts
frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
frontend/src/contexts/TeamPlaceContext.tsx
frontend/src/mocks/handlers/calendar.ts
frontend/src/mocks/handlers/feed.ts
frontend/src/mocks/handlers/link.ts

> close #620 
초기 teamPlaceId가 유효한 값인지 확인하는 로직 추가.
이외의 상황에서 403에러가 발생할경우 team select 페이지로 이동하도록 수정

[FE] 잘못된 팀플레이스 ID로 요청하는 것 막는 기능 추가

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/main/java/team/teamby/teambyteam/feed/application/NotificationService.java
backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
backend/src/main/java/team/teamby/teambyteam/feed/presentation/FeedThreadController.java
backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleCreateEvent.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleDeleteEvent.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleEvent.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleUpdateEvent.java
backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/SharedLinkCreateEvent.java
backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/SharedLinkDeleteEvent.java
backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/SharedLinkEvent.java
backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
backend/src/test/java/team/teamby/teambyteam/feed/application/NotificationServiceTest.java
backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
backend/src/test/java/team/teamby/teambyteam/sharedlink/application/SharedLinkServiceTest.java

> close #658 close #659
- 스레드 조회시 필요 필드 추가
- isMe 필드 추가 (작성자인지 확인)
- 알림의 경우 모든 isMe필드는 `false`
-images필드 추가
- 기능구현은 안함
- 일단 무조건 빈 배열 반환
- 기능추가시 관련 테스트 추가 및 변환 로직 추가 필요
- 일정 추가/변경/제거시 알림 제거
- 관련 `Event`, `Service`에 `@Deprecated` 추가
- 관련 테스트에 `@Disabled` 추가
- event publish 제거
- 피드조회시 나가는 쿼리 변경
- 기존 : `select ~~ from member_team_place where member.id = ? and teamplace.id = ?`
- 조회 타입 : `index_merge`
- 해당 쿼리를 매 스레드마다 조회 (만약 20개의 스레드 조회시 20회 `select`)
- 변경 : `select ~~ from memeber_team_place where teamplace.id = ?`
- 조회 타입 : `ref`
- 피드조회시 최초만 조회하여 `Map`으로 팀원들 정보 캐싱
피드조회시 피드와 알림간의 관계, 피드 도메인 -> response로의 맵핑 과정에서 레거시라고 불리만한 맘에 안드는 코드들이 많이 생김..
해당 부분은 프런트와 알림에 대한 비지니스적인 회의를 지속해서 하고, 해당 내용이 결정되면 추가적일 알림피드를 구현하며 리펙터링을 하는것이 좋을것이라고 생각합니다..

[BE] 피드스레드 조회 api 응답 수정 및 이벤트 제거, 최적화

---

frontend/src/components/feed/Thread/Thread.styled.ts
frontend/src/components/feed/Thread/Thread.tsx

> close #695 
팀피드에서 스레드 크기가 너무 커서 조금 줄였습니다
글씨크기는 여전히 모아보기보단 조금 커요 (2px)

[FE] 팀피드 스레드 크기 수정

---

frontend/src/components/feed/NoticeThread/NoticeThread.stories.tsx
frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts

> close #709 
스레드 높이 조정으로 해결했습니다.

[FE] 공지 md 사이즈에서 글 잘리는 현상

---

backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
backend/src/main/java/team/teamby/teambyteam/member/application/event/MemberLeaveEvent.java
backend/src/main/java/team/teamby/teambyteam/token/application/TokenEventListener.java
backend/src/main/java/team/teamby/teambyteam/token/domain/TokenRepository.java
backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
backend/src/test/java/team/teamby/teambyteam/token/domain/TokenRepositoryTest.java

> closed #692 
* Member <-> Token 1:1 관계
* 엔티티에서 Token이 연관관계 주인으로 설정 `@JoinColumn(name = "member_id", nullable = false)`
* 따라서, DB에서 TOKEN 테이블에서 member_id를 FK로 가짐
* 이때, 기존 회원 탈퇴 비즈니스 로직에서는 단순히 MEMBER 테이블의 회원만을 delete함
* DB단에서 TOKEN 테이블에 member_id가 FK로 있으므로 데이터 정합성을 위한 제약으로 오류 발생
-> 따라서, 토큰 테이블의 해당 멤버의 토큰을 먼저 삭제 후에 멤버를 삭제해야 했다.
---
먼저 크게 2가지 방법이 있었다.
1. JPA의 cascade 옵션 사용
2. 회원 탈퇴 비즈니스 로직에 Member Delete 전에 해당 멤버의 Token 먼저 Delete
Token Entity의 Member 필드는 다음과 같이 설정되어 있다.
```java
public class Token {
...
@OneToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "member_id", nullable = false)
private Member member;
...
}
```
이때, 비즈니스 로직을 구현하기 위해 cascade 옵션을 설정해도 의미가 없다.
왜냐하면, Token 클래스에서 Member에 cascade 옵션을 설정하면 전이 주체가 Token이 되어서
Token이 삭제될 때 Member가 삭제될 것이기 때문이다.
물론 회원탈퇴 로직에서 Token만을 delete 하면 로직이 …

[BE] 회원탈퇴 오류 수정 (회원 탈퇴 이벤트 구현)

---

frontend/src/hooks/team/useTeamFeedPage.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

> close #708 close #707 
shift/ctrl/alt +enter로 개행이 가능합니다.
맥에서 option +enter로 개행이 되는지 확인해주셔야합니다.

[FE] ctrl,alt + enter로 개행기능 추가

---

frontend/src/components/feed/DeletableThumbnail/DeletableThumbnail.stories.tsx
frontend/src/components/feed/DeletableThumbnail/DeletableThumbnail.tsx
frontend/src/components/feed/ImageAddButton/ImageAddButton.stories.tsx
frontend/src/components/feed/ImageAddButton/ImageAddButton.styled.ts
frontend/src/components/feed/ImageAddButton/ImageAddButton.tsx
frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.stories.tsx
frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.tsx
frontend/src/components/feed/ThumbnailList/ThumbnailList.stories.tsx
frontend/src/components/feed/ThumbnailList/ThumbnailList.styled.ts
frontend/src/components/feed/ThumbnailList/ThumbnailList.tsx
frontend/src/constants/feed.ts
frontend/src/hooks/team/useTeamFeedPage.ts
frontend/src/hooks/thread/useImageUpload.tsx
frontend/src/hooks/thread/useImageUploader.tsx
frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
frontend/src/types/feed.ts

> close #634, close #636, close #638
본 PR에서는 이미지를 로컬에 업로드할 수 있는 기본적인 기능들을 구현하였다. 로컬에 업로드만 가능할 뿐, 실제로 서버로 이미지에 대한 정보를 보내는 기능은 포함하지 않음에 유의한다.
수행한 작업들은 아래와 같다.
- `AddImageButton` : 실제로 클릭을 했을 때 파일 선택 프롬프트가 뜨고, 파일 변경 시 이벤트가 실행되도록 구현하였다.
- `DeletableThumbnail` : 받는 `props` 가 변경되었다.
- `ImageUploadDrawer` : 피드 페이지와 결합하면서 필요없는 속성들을 지우고, `bottom` 속성 등을 추가해 메인 컴포넌트와 끼워 맞추었다 (피드 페이지의 채팅방이 `padding` 으로 감싸져 있어서 `absolute` / `width: 100%`를 썼음에도 정확히 맞지 않아서 위치를 맞추는 작업이 추가로 필요했음)
- `z-index` 를 사용해서 서랍장이 활성화되면 채팅창 위로 스르륵~ 나오게 하도록 구현했음
- 프롬프트가 열렸을 시 이미지 파일만 고르도록 자동으로 조정
- 여러 장의 이미지를 한꺼번에 올리는 것이 가능함
- 이미지를 여러 번 등록해도 덮어씌워지지 않도록 개선 (`File[]` 형태로 관리)
- 이미지가 추가되면 (`File[]` 의 내용물이 변동되면) 미리보기 이미지를 커스텀 훅에서 반환하여 보여줄 수 있도록 구현
- 이미지에 대응되는 `uuid` 를 이용해 원하는 이미지 하나를 삭제할 수 있음
- 모든 이미지를 삭제할 수 있음
- 새롭게 이미지를 등록했을 때 기존 이미지와 …

[FE] 이미지를 로컬에 업로드할 수 있는 기능 구현

---

frontend/src/apis/http.ts
frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
frontend/src/hooks/schedule/useScheduleAddModal.ts
frontend/src/hooks/schedule/useScheduleEditModal.ts
frontend/src/mocks/fixtures/schedules.ts
frontend/src/mocks/handlers/calendar.ts

> close #352 close #354 
캡쳐할 때는 toast 문구가 200자 제한인데 실제로 DB제한이 255자라고 해서 250자 제한으로 문구 바꿨습니ㅏㄷ.
전
후

[FE]일정 제목이 길때 등록안되는 버그

---

backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImage.java

> 긴급이라 이슈 X
FeedThreadImage PK 전략 IDENTITY (AUTO_INCREMENT)로 수정
기존에는 
```java
@Id
@GeneratedValue
private Long id;
```
이렇게 @GeneratedValue의 전략을 지정하지 않아서 
스프링 애플리케이션 실행했을 때 다음과 같은 테이블이 추가로 생성되는 걸 확인함!
(지정하지 않으면 AUTO로 되는데, SEQUENCE 전략이 사용되는 거 같음)
```java
create table feed_thread_image_seq (
next_val bigint
) engine=InnoDB
```
그래서 IDENTITY로 전략 변경하여 AUTO_INCREMENT 사용
그래서 아래와 같은 에러가 떴음
그런데, @GeneratedValue 전략을 지정하지 않아서 AUTO로 되면, DB Dialect에 따라서 기본 전략이 사용된다고 하는데
MySQL은 기본이 IDENTITY를 사용한다고 하는데 왜 SEQUENCE로 되는지 모르겠음

[BE] FeedThreadImage PK 전략 IDENTITY (AUTO_INCREMENT)로 수정

---

backend/src/main/java/team/teamby/teambyteam/filesystem/awss3/S3Uploader.java

S3업로드 후 cloud-front 배포 url반환 오류 수정
-> url 에 s3 root directory가 추가됨. -> 해당 부분 제거

[BE] S3업로드 후 배포 도메인 반환 오류 수정

---

backend/build.gradle
backend/src/main/java/team/teamby/teambyteam/filesystem/awss3/CloudfrontCacheInvalidator.java
backend/src/main/java/team/teamby/teambyteam/filesystem/awss3/S3Uploader.java
backend/src/main/java/team/teamby/teambyteam/filesystem/awss3/configuration/S3Configuration.java
backend/src/main/resources/application.yml
backend/src/test/resources/application.yml

> closed #736
- cloudfront 의존성 추가
- CloudFrontCacheInvalidator 빈 생성
캐시제거 위치 : S3FileUploader
이유
- 케시제거에 대한 내용은 aws + cloud front라는 특수한 상황이깅에 생긴 일이라고 생각
- 다른 서비스를 이용한다면 케시제거가 그때도 무조건 필요하다는 보장 없음
- 그래서 추상화하여 비지니스 서비스에서 사용하지 않고 s3업로더에서 사용할 수 있도록 구현

[BE] S3파일 업로드 후  cloud-front 캐시 제거 기능 구현

---

backend/src/test/java/team/teamby/teambyteam/icalendar/acceptance/IcalendarAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListenerTest.java

Icalendar 테스트 코드 수정
- 이벤트 발행이 아닌 테스트 메서드 직접 실행 기반으로 테스트
- 이유 : 혹시 동일 이벤트를 listen하는 다른 리스너가 생길 경우 테스트에 영향을 미칠 수 있다고 생각
- 메서드 직접 호출이기에 TestTransaction을 커밋하는 부분 제거
AOP 실행 조건 변경
기존 : Async 어노테이션이 붙은 메서드 이후
변경 : 실행할 특정 메서드 직접 지정
이유 : 이후에 다른 Async 메서드가 생기더라도 테스트에 영향을 미치지 않게 하기 위해서
ps 드디어 블로그 작성함
테스트 관련 내용은 본 글에서 정리되어있음!!!
[블로그](https://pilyang.github.io/posts/test-async-method/)

[BE] Icalendar 테스트 수정

---

frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
frontend/src/hooks/useCalendar.ts

> close #746 
캘린더 사용하다보니 오늘 표시 없어서 불편했음

[FE] 팀 캘린더에 오늘 표시 추가

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/main/java/team/teamby/teambyteam/feed/application/ImageUploadService.java
backend/src/main/java/team/teamby/teambyteam/filesystem/FileCloudUploader.java
backend/src/main/java/team/teamby/teambyteam/filesystem/awss3/S3Uploader.java
backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishService.java
backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
backend/src/test/java/team/teamby/teambyteam/icalendar/acceptance/IcalendarAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishServiceTest.java
backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
backend/src/test/java/team/teamby/teambyteam/notice/docs/NoticeApiDocsTest.java

> 이슈 X
- S3 파일 업로드 시 content-type을 지정하지 않고 요청을 보내서 기본 `application/octet-stream`이 사용됨
- 그래서 아마 S3(CloudFront) URL로 접근 시 파일이 뜨는게 아닌 다운로드가 된 것 같음.
- upload 파라미터에 originalFileName을 받아서 다음과 같은 로직으로 MediaType추출
`final MediaType mediaType = MediaType.parseMediaType(Files.probeContentType(Paths.get(originalFileName)));`

[BE] 파일 업로드 시 content-type 추가

---

backend/src/main/java/team/teamby/teambyteam/TeamByTeamApplication.java
backend/src/main/java/team/teamby/teambyteam/auth/presentation/TeamPlaceParticipationInterceptor.java
backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/main/java/team/teamby/teambyteam/feed/application/event/FeedWriteEvent.java
backend/src/main/java/team/teamby/teambyteam/sse/application/SseSubscribeService.java
backend/src/main/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisher.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterId.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEventId.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceSseEvent.java
backend/src/main/java/team/teamby/teambyteam/sse/presentation/SseController.java
backend/src/main/resources/application.yml
backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
backend/src/test/java/team/teamby/teambyteam/sse/TestEvent.java
backend/src/test/java/team/teamby/teambyteam/sse/application/SseSubscribeServiceTest.java
backend/src/test/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisherTest.java
backend/src/test/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepositoryTest.java
backend/src/test/resources/application.yml

> close #753
- SSE 연결하여 피드 실시간 정보 전달
- SSE관련 기능들은 모두 SSE패키지에 유지
- `SseSubscribeService` : 사용자가 SSE 연결 요청시 연결 생성
- `TeamPlaceSsePublisher` : 팀플레이스 관련 이벤트 발생시 연결된 해당 팀플레이스 사용자들에게 SSE 발행
- 해당 SSE로 발행할 모든 이벤트는 TeamPlaceSseEvnet를 구현하여 사용
- 의존성 방향 통일 : `SSE` <- `domain` 으로 이벤트를 발행시킬 도메인이 sse에 대한 의존성만 가질 수 있도록 구현
- 추후 새로운 이벤트 발행시 sse패키지는 수정 없이 반영 가능

[BE] 피드 실시간 적용 - SSE

---

frontend/src/hooks/queries/useSSE.ts

> #772
아마도 연결이 끊긴것도 에러로 받아서 닫아버리면 브라우저가 다시 연결을 시도하지 못하는것 같습니다

[FE] 에러발생시 연결 끊는로직 제거

---

.github/workflows/frontend-deploy-storybook.yml

> close #769 
gh-page를 안쓰고 있는김에 배포합니다.
특정파일을 제외하거나 특정 submodule를 제외한 채로 netilfy배포가 불가능합니다. 백엔드 security 모듈이 private상태라 접근이 불가능해 현재 스토리북 배포가 진행되고있지 않습니다.
되는지 안되는지 모름 해봐야함

[FE] git page로 storybook 배포

---

backend/src/main/java/team/teamby/teambyteam/global/configuration/EnableAsyncConfiguration.java
backend/src/main/java/team/teamby/teambyteam/sse/application/SseSubscribeService.java
backend/src/main/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisher.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
backend/src/main/java/team/teamby/teambyteam/sse/presentation/SseController.java
backend/src/main/resources/application.yml
backend/src/test/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisherTest.java
backend/src/test/resources/application.yml

- application.yml 설정파일을 통해서 connection timeout을 설정할 수 있도록 변경
- lastEventId를 가져오는 방식을 RequestHeader -> RequstParam으로 변경
- 실제 요청 확인시 `lastEventId`라는 이름의 쿼리파람으로 날라옴

[BE] SSE connection timeout 설정 위치 변경

---

frontend/src/components/feed/Carousel/Carousel.styled.ts
frontend/src/components/feed/Carousel/Carousel.tsx
frontend/src/components/feed/CarouselImage/CarouselImage.stories.tsx
frontend/src/components/feed/CarouselImage/CarouselImage.styled.ts
frontend/src/components/feed/CarouselImage/CarouselImage.tsx
frontend/src/components/feed/DeletableThumbnail/DeletableThumbnail.tsx
frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
frontend/src/components/feed/PageIndicator/PageIndicator.styled.ts
frontend/src/components/feed/ThreadImageModal/ThreadImageModal.styled.ts
frontend/src/components/feed/ViewableThumbnail/ViewableThumbnail.tsx
frontend/src/mocks/fixtures/threads.ts
frontend/src/styles/theme.ts

> close #750
- styled-components prop 관련 리팩토링은 미포함
본 PR에서는 이미지가 깨지는 상황에 보다 유연하게 동작할 수 있도록, 이미지가 깨질 경우에 대한 예외처리가 가능하도록 개선하였다. 이미지가 깨지는 원인은 다양하지만 백엔드에서 잘못된 형식의 이미지를 내려주는 경우, 인터넷 연결이 불안정해 이미지의 로딩이 실패하는 등 여러 요인이 있을 것이다.
- 여기서 이미지가 **깨진다** 는 것은, 이미지가 만료되지는 않았으나 손상된 이미지의 `src` 를 지니게 되어 이미지가 보이지 않고 `alt` 텍스트가 보이는 문제를 의미한다.
1. 썸네일 컴포넌트에 보여져야 하는 이미지가 깨졌을 경우, 만료되었을 때와 마찬가지로 대체 이미지를 보여주도록 개선하였다.
2. 이미지 모달에 보여져야 하는 이미지가 깨졌을 경우, 이미지가 깨졌음을 알리는 대체 텍스트를 대신 띄워 사용자에게 이를 알릴 수 있도록 개선하였다.
1. 이미지 서랍장 모달이 정확하게 맞지 않아 위치를 교정하였다.
2. @suyoungj 의 제안으로 이미지 모달의 디자인을 좀 더 프로젝트에 연관성이 있도록 수정해 보았다.
- UX에 무리가 가지 않는 선에서 제목/닫기 버튼/인디케이터의 크기 축소
- 배경색을 밝게 하고, 다소 투명하게 변경
3. `theme` 파일의 HEX 코드를 모두 영소문자로 통일하였다.
- 1번 기능
- 2번 기능
여담으로 이미지 모달의 경우 `blur` 가 처음부터 있는 상황이었더라...?

[FE] 이미지가 깨지는 경우에 대해 적절히 예외처리 할 수 있도록 개선

---

frontend/src/hooks/queries/useFetchICalendarUrl.ts
frontend/src/mocks/handlers/calendar.ts

- iCalendar url에 placeholder 적용하여 빈 input을 보지 않도록 수정
- url이 고정되어 있으므로 빈 input 대신 url 일부를 사용자에게 미리 보여줌

[FE] iCalendar url에 placeholder 적용하여 빈 input을 보지 않도록 수정

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/cache/InMemoryRecentFeedCache.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/cache/RecentFeedCache.java
backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadWithCacheServiceTest.java
backend/src/test/java/team/teamby/teambyteam/feed/domain/cache/InMemoryRecentFeedCacheTest.java

> #774
- 피드 최신정보 조회시 인메모리 캐시에서 글 읽어올 수 있도록 변경
- 캐시정보 없을시 db에서 정보조회
- 캐시정보는 피드 작성시 같이 추가
- 3일이상 활동이 없는팀에 한해 캐시 제거

[BE] 피드 최신조회에 인메모리 캐싱 추가

---

backend/src/main/java/team/teamby/teambyteam/sse/application/SseSubscribeService.java
backend/src/main/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisher.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java
backend/src/main/java/team/teamby/teambyteam/sse/presentation/SseController.java
backend/src/test/java/team/teamby/teambyteam/icalendar/acceptance/IcalendarAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/sse/application/SseSubscribeServiceTest.java
backend/src/test/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepositoryTest.java

> close #773
- SSE 연결시 캐시된 이벤트 전달 및 이벤트 발행시 캐시 저장 기능 제거
- 재연결시 프런트에서 요청을 보내는것으로 전환해서 일단 캐시 제거
- 추후 필요시 다시 기능구현 후 추가 예정
- 이때는 프런트에서 연결이 되었음을 다시 전달해주고, 연결이 완료된 후 캐시를 한번에 보내는식으로 발행할 필요 있음
- SSE subscribe 요청에 대한 응답에 `Keep-Alive: timout={time}`헤더 추가
- 문제가 생긴 원인
- sse 연결 유지 도중 1분(약 45초)간 발행된 이벤트가 없을시 스프링에서 `SseEmitter`생성시 설정한 timeout이 지나기 전에 클라이언트에서 연결종료 후 재연결시도
- 이때 기존 연결이 서버인스턴스에 `close_wait`상태로 유지중으로 리소스를 계속 잡아먹음
- 일단 개발서버에 해당 헤더를 추가해서 올려보고, 5분간 이벤트가 없어도 연결이 유지되면 이대로 유지, 안된다면 슬랙에 공유한 방법중 한가지를 선택하여 그대로 변경 예정
- 슬렉에 공유한 내용 간단 정리
- spring SseEmitter timout시간을 1분으로 설정한다.
- 생성된 connection들에 30초마다 (브라우저가 45초가 되는 시점에 재연결을 해서) dummy이벤트를 발행한다

[BE] SSE 연결시 케시전송 제거 및 Keep-Alive 설정 추가

---

frontend/src/components/common/Header/Header.tsx

> close #826 
- 팀 정보 아이콘 onFocus, onMouseEnter시 prefetching 적용
- onFocus / onMouseEnter가 일어나면 사용자가 클릭할 것이라 가정하고 데이터를 미리 불러와서 로딩 상태를 보지 않도록 구현했습니다
- 아이디어는 저번에 요토랑 잡담하다 갑자기 생각났습니다

[FE] 팀 정보 아이콘 접근 시 prefetching 적용

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
backend/src/main/java/team/teamby/teambyteam/feed/application/event/FeedEvent.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceConnectedEvent.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterId.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceSseEvent.java
backend/src/main/java/team/teamby/teambyteam/sse/presentation/SseController.java
backend/src/test/java/team/teamby/teambyteam/sse/TestEvent.java

> close #781
- 기존에 있던 `FeedResponse`재활용
- 이벤트 수신자가 피드 작성자인지 확인하기 위해서 `TeamPlaceSseEvent`에서 이미터 아이디를 받아 수신자 아이디에 따라 메시지 다르게 전송하도록 구현 변경
- 인터페이스의 메서드 선언 변경
- `FeedEvent`에서 authorId와 memberId를 비교하여 isMe필드가 변경된 객체를 재생성하여 반환하도록 구현 변경
- 처음에는 작성자가 다른경우의 이벤트발행이 많아 isMe를 기본으로 false로 두고 멤버앙디가 일치하는 경우만 재생성하여 리소스를 줄이도록 설계하였지만, 지금 있는 코드를 최대한 재사용하며 주석없이 `FeedEvent` 내의 `isMe`필드가 false임을 표현하기 어려워서 매번 재생성 하도록 구현. (햇갈릴까봐~)
피드작성 서비스 가독성 생각해서 소소한 리팩터링 했는데, 전반적으로 건들기는 작업이 커질것같아서 일단 보류했습니다.

[BE] 피드작성 이벤트에 작성된 피드 내용 포함

---

frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
frontend/src/hooks/queries/usePrefetchMySchedules.ts

> close #850 
- 내 일정 캘린더에 Prefetching 적용
- 방식은 팀 캘린더와 동일합니다

[FE] 내 일정 캘린더에 Prefetching 적용

---

frontend/src/hooks/queries/useModifyUserInfo.ts
frontend/src/hooks/user/useUserInfoModal.ts

> close #848 
- 프로필 닉네임 수정 낙관적 업데이트 적용
https://tanstack.com/query/v4/docs/react/examples/react/optimistic-updates-typescript
- MSW delay 1초 줘서 결과 비교
- 낙관적 업데이트 X
- 낙관적 업데이트 O

[FE] 프로필 닉네임 수정 낙관적 업데이트 적용

---

frontend/src/components/feed/Carousel/Carousel.styled.ts
frontend/src/components/feed/Carousel/Carousel.tsx
frontend/src/components/feed/ThreadImageModal/ThreadImageModal.tsx
frontend/src/constants/feed.ts
frontend/src/hooks/thread/useCarouselPageNo.ts

> close #834 
본 PR에서는 팀 채팅 메뉴에서 쓰이는 이미지 모달의 이미지를 키보드 조작으로도 가능하게 만들어 사용자가 보다 편리하게 기능을 사용할 수 있도록 개선하였다.
- `←`, `→` 키를 누르면 이미지를 양옆으로 전환할 수 있다.
- `1` ~ `9` 키를 누르면 누른 숫자 키에 해당하는 번호의 이미지를 보여 준다. 단, 전체 이미지 개수보다 누른 키의 번호가 클 경우에는 아무 일도 일어나지 않는다.
- 모달의 이미지가 하나뿐인 경우, 양옆의 이미지 전환 버튼을 비활성화시키고 시각적으로도 전환이 불가능함을 표현하였다.
- 이미지가 하나뿐이었을 때 버튼이 비활성화되어 시각적으로도 흐리게 표시되며, 마우스 포인터도 `not-allowed` 로 표시된다.
구현 중 `keyDown` 이벤트의 `keyCode` 를 사용했는데, 이 프로퍼티는 사실 deprecated된 프로퍼티로, 사용이 권장되지 않는 상태야. 그럼에도 사용했는데, 이유는 [이 이슈](https://github.com/wzrabbit/boj-totamjung/issues/11)에서 트러블슈팅을 했을 때, 일부 Mac OS 유저에 한해, `key` 프로퍼티에 찍히는 값이 이상한 경우가 간혹 있었더라고.
그래서, 기본적으로 사용이 권장되는 `key` 프로퍼티를 통해 눌린 키가 방향키/숫자키인지 검사하되, 아닐 경우에 `keyCode` 를 사용하여 보조적으로 추가 검증을 하는 방향으로 구현해 보았어.
내가 명확하게 권장되지 않는 걸 쓴 것은 맞으니, 이에 대해서 의논해 보면 좋을 것 같아!

[FE] 이미지 모달의 이미지 전환을 키보드 조작으로 할 수 있도록 개선

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedRepository.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedThread.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
backend/src/main/java/team/teamby/teambyteam/notice/domain/Notice.java

- 피드조회시 쿼리 N+1문제 최적화
eager -> lazy로 전환 (eager로 있으면 후에 jpql로 조회시에도 이미지를 가져오려 해서 n+1생길 여지 있음 + 사이드이펙트들이 있을 수 있음)
`@BatchSize`를 통해서 n+1제거
- size = 20
- 비지니스규칙이 매번 20개의 피드만 조회함으로 20개로 지정
BatchSize 20으로 조회시 쿼리
`@EntityGraph`를 통하여 fetch join을 하여 MemberTeamPlace 조회시 Member를 같이 조회할 수 있도록 변경
의논할거리까지는 아니고 이미지 문제를 해결할때 Pagable에서의 해결방법이 BatchSize, Fetch(FetchType.SUBSELECT)가 있었는데 BatchSize를 선택한 이유는 아래와 같음
BatchSize시의 쿼리는 위에 첨부를 함 만약에 이게 subselect방식을 이용하게 된다면
위와같이 나오게 됨.
복잡성이 너무 증가하게 되어서 BatchSize가 더 좋다고 판단 + 우리 비지니스상 BatchSize가 20정도로 100 이상처럼 많은 값으로 갈 필요도 없다고 생각을 해서 위와같은 구현을 결정

[BE] 피드조회시 쿼리 최적화

---

backend/src/main/java/team/teamby/teambyteam/sse/application/SseSubscribeService.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java
backend/src/test/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisherTest.java

- SSE 발행시 스레드 분리 제거
- 제거 이유
- 프런트에서 중복으로 연결 요청하는 버그 수정 후 연결 관리가 어느정도 됨
- 멀티스레드로 인한 성능테스트가 아직 안되어서 일단 TeamPlace 이벤트 하나당 스레드 하나 사용하도록 복귀 -> 후에 성능문제시 정략적인 테스트 후 스레드 분리 다시 고려
- Sse관련 클래스들 리팩터링
- 중복로직 메서드 분리
- 로깅 가독성 향상시켜서 디버깅 쉽게 변경
- 미사용 메서드 제거

[BE] SSE 관련 기능들 리팩터링 및 멀티스레드 제거

---

backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListener.java
backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishScheduler.java
backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishService.java
backend/src/main/java/team/teamby/teambyteam/icalendar/application/PeriodicIcalendarPublishService.java
backend/src/main/java/team/teamby/teambyteam/icalendar/domain/IcalendarPublishCounter.java
backend/src/main/java/team/teamby/teambyteam/icalendar/domain/PublishedIcalendarRepository.java
backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListenerTest.java
backend/src/test/java/team/teamby/teambyteam/icalendar/domain/IcalendarPublishCounterTest.java

> close #796
- icalendar 배포 주기 조절 기능 구현
- 배포 방식
- 1시간에 최대 10회까지는 일정 변동시 자동 업데이트 배포
- 1시간에 10회 이상 요청시에는 배포 안하고 대기
- 매시 45분에 지난 1시간동안 10회 이상 변경요청이 들어온 팀 일괄 배포
`IcalendarPublishCounter` : 팀플레이스당 최근 1시간동안 배포 요청 수 카운트
~~`IcalendarEventListener` : 일정변동 & 업데이트 이벤트 발생시 `배포카운터`가 10회 미만시 배포진행, 카운터 추가 + 10회 이상시 ics배포 취소~~
~~`IcalendarPublishScheduler`: 매시 45분에 밀린 배포요청 처리 후 카운터 초기화`~~
`PeriodicIcalendarPublishService`
- 1시간 주기동안은 카운터에서 지정한 횟수 미만의 업데이트 요청만 업데이트 배포 처리
- 매시 45분 딜레이된 배포 일괄 수행
`IcalendarEventListner`
- 기존 : IcalendarPublishService를 통해 ics 배포 수행
- 변경 : PeriodicIcalendarPublishService를 통해 ics 배포 수행
45분에 업데이트인 이후
- 대다수의 캘린더 클라이언트 프로그램이 ics파일 일정을 매시 정각에 업데이트를 하기 때문에 정각이 되기 일정 시간 전에 업데이트 후 카운터 초기화를 해둬야 정각에 외부 캘린더에서 일정을 가져올때 최신 정보를 가져올 확률이 높다고 판단하였음
1. 1시간동안 변동되는 모든 팀플레이스 캐싱 후 매시간 1회만 업데이트 진행 …

[BE] 일정변동이 잦은 경우 ics배포 

---

frontend/src/apis/feed.ts
frontend/src/constants/query.ts
frontend/src/hooks/queries/useFetchThreads.ts
frontend/src/hooks/queries/useSSE.ts

> close #836 
queryClient.setQueryData를 이용해봄
되는지 안되는지는 확인해봐야함
https://tanstack.com/query/v4/docs/react/reference/QueryClient#queryclientsetquerydata

[FE] sse 발생시 팀 채팅 조회로직 제거 밑 이벤트 이용해 채팅 렌더링

---

backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/LocalDateParser.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleService.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
backend/src/main/java/team/teamby/teambyteam/schedule/application/parser/LocalDateParser.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleException.java
backend/src/main/java/team/teamby/teambyteam/schedule/presentation/MyCalendarScheduleController.java
backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamCalendarScheduleController.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MyCalendarScheduleAcceptanceFixtures.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamCalendarScheduleAcceptanceFixtures.java
backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/MyCalendarScheduleAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/LocalDateParserTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleServiceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
backend/src/test/java/team/teamby/teambyteam/schedule/domain/CalendarPeriodTest.java

> close #884
- 지정된 범위로 일정 조회 기능 구현
- 팀내일정, 개인일정 모두 구현
- 기존 일정조회 url에서 쿼리파라미터에 `startdate`, `enddate`인 api 각각 추가
- 팀일정 : `/api/team-place/{teamPlaceId}/calendar/schedules?startdate=yyyyMMdd&enddate=yyyyMMdd`
- 내일정 : `/api/my-calendar/schedules?startdate=yyyyMMdd&enddate=yyyyMMdd`
- 쿼리 모두 필요
- 일정형식이 yyyyMMdd 8글자 형식이 아니면  `BAD_REQUEST`
- startdate, enddate에서 enddate가 더 이른 경우 `BAD_REQUEST`
- 응답은 기존 API와 동일형식
자세한 명세는 노션 API 명세 페이지 테이블 참고

[BE] 특정 기간을 지정해서 일정 조회 기능 구현

---

frontend/src/components/feed/ThreadList/ThreadList.tsx
frontend/src/hooks/queries/useSSE.ts

> close #883 
본 PR에는 채팅이 렌더링 되지 않는 현상에 대한 코드가 없습니다. 
해당 PR의 변경은 채팅 이벤트 발생 시 스크롤이 맨 하단이 볼 수 있도록 하는 작업과 SSE가 연결되었을 때 채팅쿼리를 무효화하는 작업만 존재합니다. 따라서 버그를 수정한 것+ 그동안 변경된 부분에 대해서는 아래에 자세히 작성하도록 하겠습니다.
---
```
//초기 문제가 되었던 부분 useSSE.ts
queryClient.setQueryData<ThreadsResponse>(
['threadData', teamPlaceId],
(old) => {
if (old) {
return { threads: [...old.threads, newThread] };
}
```
채팅이 렌더링 되지 않았던 이유입니다. 
해당 문제는 threadData가 무한스크롤형태의 데이터인데 그냥 조회쿼리의 응답값으로 쿼리 데이터를 저장해서 발생했습니다.
이를 무한데이터 형식으로 타입을 지정해주고 지정한 타입에 맞춰 데이터를 저장하도록 변경하여 해결했습니다.
#886 
```
// 문제 해결을 위해 수정된 부분 useSSE.ts
queryClient.setQueryData<InfiniteData<ThreadsResponse>>(
['threadData', teamPlaceId],
(old) => {
if (old) {
old.pages[0].threads = [newThread, ...old.pages[0].threads];
return old;
}
}
```
---
이후 콘솔로 확인해본결과 채팅데이터는 적절히 수정되고 있는데 …

[FE] 채팅 변경되었을 시 스크롤 하단 볼 수 있도록 수정

---

frontend/src/components/link/LinkTable/LinkTable.styled.ts
frontend/src/components/link/LinkTable/LinkTable.tsx
frontend/src/mocks/handlers/link.ts

> close #891 
해당 버그는 팀링크에서 일어난 버그입니다.
이는 테이블 자체가 팀링크의 유무에 따라 있거나 없어지게 되어있기 때문이었습니다. 
해당 PR에서는 이를 해결하고 기존의 잘못된 table 구조때문에 일어나던 아래의 오류를 해결했습니다.

[FE] 팀 링크 레이아웃 버그 픽스

---

frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
frontend/src/utils/generateDateTimeRangeDescription.ts
frontend/src/utils/test/generateDateTimeRangeDescription.test.ts

> close #904 
본 PR에서는 일정을 클릭할 경우 표시되는 문구를 좀 더 깔끔한 문구로써 보이도록 개선하였다. 구체적으로는 아래의 사항을 개선하였다.
1. `2023-01-03 00:00 ~ 2023-01-03 23:59` 와 같은 하루짜리 종일 일정은 `2023-01-03` 과 같이 변경하였다.
2. `2023-01-03 00:00 ~ 2023-01-07 23:59` 와 같은 여러 날짜리 종일 일정은 `2023-01-03 ~ 2023-01-07` 과 같이 변경하였다.
3. `2023-01-03 03:00 ~ 2023-01-03 03:00` 와 같은 시작 일정과 마감 일정이 완전히 같은 경우에는 `2023-01-03 03:00` 과 같이 변경하였다.
4. 위의 어떠한 경우에도 속하지 않는 경우는 본래의 일정 정보를 그대로 보여준다.
3번 케이스의 경우 현재 PR 기준으로 같은 시간으로 시작해 같은 시간으로 끝나는 일정을 생성할 수 없도록 아직 막혀있으므로 `msw` 등의 모킹 데이터를 이용하여 테스트해 보아야 변경 사항이 보일 것이다. 유틸 함수의 테스트 코드를 구현한 것도 작동함을 보이기 위함이다.
의논했던 요구사항에 기반하여 구현했지만 좀 더 개선할 수 있어보여서 조건을 더 만들고 문구도 더 추가해 보았어. 어떤 것 같아?

[FE] 일정 표시 문구 개선

---

frontend/src/components/feed/ThreadList/ThreadList.tsx

> #892 
#775 에서 추가되었던 threadPage length 비교가 도대체 왜 필요했었던걸까? 로직이 이해가 안돼,,, 비슷하게 하면 돌아가겠지라고 생각해서
#888 에서 기존 페이지 수로 비교하던 것을 page 안의 thread수로 비교하게끔 한거거든
스크롤 할때 이 로직이 필요했을까? 라는 의문이 들어서 일단 삭제해봤어
얘가 있는 이유가 있을텐데 도대체 뭐였을까 왜 비교를 하고 값을 저장했던 걸까? 왜????왜?!?!?!?!?

 [FE] 스크롤 useEffect에서 threadPage 수 비교 로직 삭제

---

frontend/src/components/my_calendar/MyDailyScheduleList/MyDailyScheduleList.tsx
frontend/src/hooks/queries/useFetchMyDailySchedule.ts

[FE] 통합하루일정이 변경된 API 명세와 다르게 요청하는 문제
> close #907

[FE] 통합하루일정이 변경된 API 명세와 다르게 요청하는 문제

---

frontend/src/components/feed/ThreadList/ThreadList.tsx

> #892 
기존 채팅 스크롤을 관리하던 useEffect의 dependency가 threadPages였는데 
이를 threadPages?.pages[0].threads.length로 변경하였다.

[FE] 채팅 스크롤 버그 픽스

---

frontend/src/App.css
frontend/src/App.tsx
frontend/src/components/common/Header/Header.styled.ts
frontend/src/components/common/Header/Header.tsx
frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.stories.tsx
frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.tsx
frontend/src/components/feed/Thread/Thread.styled.ts
frontend/src/mobilePages/M_PageTemplate/M_PageTemplate.styled.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

> close #900
모바일에서 어색하게 보였던 부분 수정
- 헤더 크기 줄임
- 네비바 크기 줄임
채팅 gap 줄이고 글씨크기 줄임
브라우저 하단에 가렸던 문제 해결을 위한 높이 계산과정 추가
https://dmstjq92.medium.com/%EB%AA%A8%EB%B0%94%EC%9D%BC-ios-safari-chrome-%EC%97%90%EC%84%9C-100vh-%EC%8A%A4%ED%81%AC%EB%A1%A4-%EC%83%9D%EA%B8%B0%EB%8A%94-%EB%AC%B8%EC%A0%9C-%EC%A2%85%EA%B2%B0-682c5e9d068d

[FE] 모바일에서 하단 메뉴 잘리는 버그 픽스

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
backend/src/main/java/team/teamby/teambyteam/notice/domain/NoticeRepository.java
backend/src/main/java/team/teamby/teambyteam/notice/domain/event/NoticeCreationEvent.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverter.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/NoticeCreatedEventConverter.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/TeamPlaceSseConverter.java
backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
backend/src/test/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisherTest.java
backend/src/test/java/team/teamby/teambyteam/sse/domain/converter/NoticeCreatedEventConverterTest.java

- 팀플레이스 내 공지 등록시 팀플레이스 SSE connection을 통해 이벤트 발행
- 발행 이벤트 정보
```
event: new_notice
data: {"teamPlaceId": 1,"threadId": 1637}
```
우선은 재조회 방식으로 정보를 읽어들여와 이벤트에는 내용 추가 안함
이유
- 공지는 피드에 비해 갱신 주기가 매우 길것으로 판단
- SSE를 발행하는데 더 리소스를 쏟기보다는 기존 api 활용 하도록 하는것으로도 충분할것이라 판단.

[BE] 팀플레이스 공지 등록시 실시간 SSE 알림 추가

---

frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx

> close #933 
- 채팅 페이지 입장시 채팅 입력창에 자동으로 포커스 하지 않도록 변경
- 이유: 메뉴에 단순 입장한 것만으로 자동 포커스가 되면, 키패드가 자동으로 열려 UX 저하를 유발할 수 있어보인다

[FE] 모바일에서 채팅 입력창에 자동으로 포커스 하지 않도록 변경

---

frontend/src/hooks/queries/useFetchThreads.ts

> close #931 
자세한 버그 상황은 이슈에 첨부하였음.
지금 채팅 이벤트를 받으면 맨 앞 스레드페이지(무한스크롤 페이지)의 맨 앞에 끼워넣고 있음.
이때 첫 로드시 채팅이벤트를 받으면  lastPage.threads.length가 THREAD_SIZE와 달라질 수 밖에없음.
(첫 로드시 lastPage는 맨 처음 페이지니까)
때문에 비교연사자를 `같지 않다`에서 `작으면`으로 바꿔 첫 로드시 lastPage가 이벤트르 받게되어 THREAD_SIZE보다 커질 것을 대비할 수 있도록 하였음.
이후 파생될 버그에대해서는 아직 예측할 수 없으니 문제가 생기면 다시 픽스하는걸로

[FE] 첫 로드 후 조회 요청 없이 채팅을 치면 조회가 안되는 버그

---

backend/src/main/java/team/teamby/teambyteam/icalendar/domain/ical4j/ICal4jParser.java
backend/src/main/java/team/teamby/teambyteam/icalendar/domain/ical4j/VEventParser.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java

> #945  
- Schedule 생성시 `Description` 필드에 null 할당 방지
- Schedule에 Description이 있는지 여부 묻는 메서드 추가
- ICS 파싱중 예외 발생시 로깅 추가

[BE] Schedule Description null 가능성 제거

---

frontend/src/components/feed/Thread/Thread.stories.ts
frontend/src/constants/link.ts

> close #953 
본 이슈에서는 팀 피드/팀 링크에서 사용되는 URL을 검증하는 정규 표현식의 조건을 완화시켜, 이름이 긴 최상위 도메인명들 또한 유효한 링크로 판정할 수 있도록 로직을 수정하였다. 
- 올바른 URL인지를 판정하는 정규 표현식의 조건을, 최상위 도메인 **2~5**자에서 **2~12**자로 조건을 수정하였다.
바뀐 URL의 조건은 팀 피드에서 입력된 링크를 하이퍼링크로 인식할 것인지, 팀 링크에서 링크를 등록할 때 올바른 URL인지를 판별하는 로직에 영향을 준다.

[FE] 팀 피드/팀 링크에서의 최상위 도메인명 조건 완화

---

backend/src/main/java/team/teamby/teambyteam/feed/application/FeedReadService.java
backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
backend/src/main/java/team/teamby/teambyteam/feed/application/event/FeedEvent.java
backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverter.java
backend/src/test/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverterTest.java

- 채팅으로 인한 sse 이벤트 발행시 채팅 내용 조회를 위한 db조회 제거
초기  db조회 없이 발행을 하도록 하였다가 코드의 일관성 (domain event) 을 위해 이벤트에는 내용등 정보 없이 이벤트 발행시 최초 1회 다시 db조회를 하도록 변경
해당 기능 구현 이후 db조회로 인한 채팅 성능의 하락이 눈에 띌 정도로 생김
일단은 사용자들의 불편함 없는 경험이 중요하다고 생각하여 db조회 없이 피드 sse 를 발행할 수 있도록 재 변경 진행

[BE] 팀채팅시 이벤트 발행에 db조회 제거

---

backend/src/main/java/team/teamby/teambyteam/common/domain/BaseEntity.java
backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/Feed.java
backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImage.java
backend/src/main/java/team/teamby/teambyteam/filesystem/exception/FileControlException.java
backend/src/main/java/team/teamby/teambyteam/filesystem/util/FileUtil.java
backend/src/main/java/team/teamby/teambyteam/icalendar/domain/PublishedIcalendar.java
backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
backend/src/main/java/team/teamby/teambyteam/member/application/dto/MemberUpdateRequest.java
backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
backend/src/main/java/team/teamby/teambyteam/notice/domain/Notice.java
backend/src/main/java/team/teamby/teambyteam/notice/domain/image/NoticeImage.java
backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceInviteCode.java
backend/src/main/java/team/teamby/teambyteam/token/domain/Token.java
backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
backend/src/test/java/team/teamby/teambyteam/sharedlink/application/SharedLinkServiceTest.java

- global -> domain pacakges -> common 방향으로 의존성 흐름 정리
- filesystem package에서 feed패키지에 의존하는 문제 해결
- Member 관련 패키지 추가 작업필요
- 인증관련해서 변화가 복잡할것으로 판단되어 PR분리
- 마찬가지로 member - memberTeamPlace - teamPlace 사이 관계도 분리

[BE] common-global package 분배, 일부 양방향 의존 해결

---

frontend/src/hooks/queries/useSSE.ts

> close #959
본 PR에서는 새로운 채팅을 입력할 때, 또는 SSE로부터 새로운 메시지를 수신받을 때 바로 새로운 채팅이 제대로 반영되지 않는 문제를 해결하였다.
- 기존 채팅의 경우 SSE로부터 새로운 메시지를 수신했을 때 수신은 감지되나 채팅이 바로 업데이트되지 않고, 사용자가 채팅창에 새로운 내용을 입력하거나, 공지 체크박스를 작동시키는 등 채팅창과 상호작용을 한 경우에 그제서야 반응되는 문제가 있었다.
- 본 PR 반영 이후에는 SSE로부터 새로운 메시지를 수신받았을 때 그 즉시 채팅창을 업데이트해 최신 채팅이 바로 보이도록 반영하였다.
원리 및 작동 화면은 하단의 코멘트에서 보충하여 설명한다.

[FE] 채팅 시 SSE에 의해 수신되는 내용이 늦게 반영되는 문제 해결
